<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>dfrtool</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <Copyright>Copyright © Synival 2026</Copyright>
    <AssemblyVersion>1.1.3</AssemblyVersion>
    <FileVersion>1.1.3</FileVersion>
    <Version>1.1.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonLib\CommonLib.csproj" />
    <ProjectReference Include="..\DFRLib\DFRLib.csproj" />
  </ItemGroup>

</Project>
