<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>SF3.Win</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyVersion>0.2.0</AssemblyVersion>
    <FileVersion>0.2.0</FileVersion>
    <Version>0.2.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Images\ApplyHideTags.bmp" />
    <None Remove="Images\ApplyShadowTags.bmp" />
    <None Remove="Images\CameraFromFront.bmp" />
    <None Remove="Images\CameraFromTop.bmp" />
    <None Remove="Images\CameraPointToCenter.bmp" />
    <None Remove="Images\CursorNavigate.bmp" />
    <None Remove="Images\CursorSelect.bmp" />
    <None Remove="Images\EventIDs.bmp" />
    <None Remove="Images\EventIDs.xcf" />
    <None Remove="Images\HideModelsFacingAway.bmp" />
    <None Remove="Images\IconWireframe.bmp" />
    <None Remove="Images\LightingNew.bmp" />
    <None Remove="Images\LightingOld.bmp" />
    <None Remove="Images\Normals.bmp" />
    <None Remove="Images\RenderOnBlackBackground.bmp" />
    <None Remove="Images\RunAnimations.bmp" />
    <None Remove="Images\ShowActors.bmp" />
    <None Remove="Images\ShowCameraBoundaries.bmp" />
    <None Remove="Images\ShowCollisions.bmp" />
    <None Remove="Images\ShowEventIDs.bmp" />
    <None Remove="Images\ShowExtraModels.bmp" />
    <None Remove="Images\ShowGradients.bmp" />
    <None Remove="Images\ShowGroundWater.bmp" />
    <None Remove="Images\ShowLighting.bmp" />
    <None Remove="Images\ShowModels.bmp" />
    <None Remove="Images\ShowSky.bmp" />
    <None Remove="Images\ShowSurfaceModel.bmp" />
    <None Remove="Images\ShowTerrainTypes.bmp" />
    <None Remove="Images\SpritesPointingUp.bmp" />
    <None Remove="Images\TerrainTypes.bmp" />
    <None Remove="Images\TerrainTypes.xcf" />
    <None Remove="Images\TileWireframe.bmp" />
    <None Remove="Images\TransparentBlack.bmp" />
    <None Remove="Images\TransparentWhite.bmp" />
    <None Remove="Images\UnknownSprite.bmp" />
    <None Remove="Images\White.bmp" />
    <None Remove="Shaders\Normals.frag" />
    <None Remove="Shaders\Normals.vert" />
    <None Remove="Shaders\Object.frag" />
    <None Remove="Shaders\Object.vert" />
    <None Remove="Shaders\Solid.frag" />
    <None Remove="Shaders\Solid.vert" />
    <None Remove="Shaders\Texture.frag" />
    <None Remove="Shaders\Texture.vert" />
    <None Remove="Shaders\TwoTexture.frag" />
    <None Remove="Shaders\TwoTexture.vert" />
    <None Remove="Shaders\Wireframe.frag" />
    <None Remove="Shaders\Wireframe.vert" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Images\ApplyHideTags.bmp" />
    <EmbeddedResource Include="Images\ApplyShadowTags.bmp" />
    <EmbeddedResource Include="Images\CameraFromFront.bmp" />
    <EmbeddedResource Include="Images\CameraFromTop.bmp" />
    <EmbeddedResource Include="Images\CameraPointToCenter.bmp" />
    <EmbeddedResource Include="Images\CursorNavigate.bmp" />
    <EmbeddedResource Include="Images\CursorSelect.bmp" />
    <EmbeddedResource Include="Images\EventIDs.bmp" />
    <EmbeddedResource Include="Images\EventIDs.xcf" />
    <EmbeddedResource Include="Images\HideModelsFacingAway.bmp" />
    <EmbeddedResource Include="Images\IconWireframe.bmp" />
    <EmbeddedResource Include="Images\LightingNew.bmp" />
    <EmbeddedResource Include="Images\LightingOld.bmp" />
    <EmbeddedResource Include="Images\Normals.bmp" />
    <EmbeddedResource Include="Images\RenderOnBlackBackground.bmp" />
    <EmbeddedResource Include="Images\RunAnimations.bmp" />
    <EmbeddedResource Include="Images\ShowActors.bmp" />
    <EmbeddedResource Include="Images\ShowCameraBoundaries.bmp" />
    <EmbeddedResource Include="Images\ShowCollisions.bmp" />
    <EmbeddedResource Include="Images\ShowEventIDs.bmp" />
    <EmbeddedResource Include="Images\ShowExtraModels.bmp" />
    <EmbeddedResource Include="Images\ShowGradients.bmp" />
    <EmbeddedResource Include="Images\ShowGroundWater.bmp" />
    <EmbeddedResource Include="Images\ShowLighting.bmp" />
    <EmbeddedResource Include="Images\ShowModels.bmp" />
    <EmbeddedResource Include="Images\ShowSky.bmp" />
    <EmbeddedResource Include="Images\ShowSurfaceModel.bmp" />
    <EmbeddedResource Include="Images\ShowTerrainTypes.bmp" />
    <EmbeddedResource Include="Images\SpritesPointingUp.bmp" />
    <EmbeddedResource Include="Images\TerrainTypes.bmp" />
    <EmbeddedResource Include="Images\TerrainTypes.xcf" />
    <EmbeddedResource Include="Images\TileWireframe.bmp" />
    <EmbeddedResource Include="Images\TransparentBlack.bmp" />
    <EmbeddedResource Include="Images\TransparentWhite.bmp" />
    <EmbeddedResource Include="Images\UnknownSprite.bmp" />
    <EmbeddedResource Include="Images\White.bmp" />
    <EmbeddedResource Include="Shaders\Normals.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\Normals.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\Object.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\Object.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\Sprite.frag" />
    <EmbeddedResource Include="Shaders\Sprite.vert" />
    <EmbeddedResource Include="Shaders\Solid.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\Solid.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\Texture.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\Texture.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\TwoTexture.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\TwoTexture.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\Wireframe.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Shaders\Wireframe.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OpenTK.GLControl" Version="4.0.1" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommonLibWin\CommonLibWin.csproj" />
    <ProjectReference Include="..\CommonLib\CommonLib.csproj" />
    <ProjectReference Include="..\DFRLib\DFRLib.csproj" />
    <ProjectReference Include="..\DFRLibWin\DFRLibWin.csproj" />
    <ProjectReference Include="..\ObjectListView\ObjectListView\ObjectListView2008.csproj" />
    <ProjectReference Include="..\SF3Lib\SF3Lib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\ActorNPCPropertiesControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\ImageControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\ActorBattlePropertiesControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\MPD_ViewerControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\MPD_ViewerGLControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\MPD_ViewerGLControl.Camera.cs">
      <DependentUpon>MPD_ViewerGLControl.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\MPD_ViewerGLControl.Editing.cs">
      <DependentUpon>MPD_ViewerGLControl.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\MPD_ViewerGLControl.KeyboardControls.cs">
      <DependentUpon>MPD_ViewerGLControl.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\MPD_ViewerGLControl.MouseControls.cs">
      <DependentUpon>MPD_ViewerGLControl.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\MPD_ViewerGLControl.Rendering.cs">
      <DependentUpon>MPD_ViewerGLControl.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\EnhancedObjectListView.Header.cs">
      <DependentUpon>EnhancedObjectListView.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\ModelInstancePropertiesControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Controls\ActorNPCPropertiesControl.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Controls\ActorBattlePropertiesControl.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Controls\ModelInstancePropertiesControl.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>