<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Copyright>Copyright © Synival 2026</Copyright>
    <AssemblyVersion>0.3.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonLib\CommonLib.csproj" />
  </ItemGroup>

</Project>
