#!/bin/bash
echo "Abdark.SF3Sprite"; ../../chrtool.exe format "Abdark.SF3Sprite" > tmp; mv tmp "Abdark.SF3Sprite"
echo "Accessory Dealer.SF3Sprite"; ../../chrtool.exe format "Accessory Dealer.SF3Sprite" > tmp; mv tmp "Accessory Dealer.SF3Sprite"
echo "Algernon (Tied_Up).SF3Sprite"; ../../chrtool.exe format "Algernon (Tied_Up).SF3Sprite" > tmp; mv tmp "Algernon (Tied_Up).SF3Sprite"
echo "Algernon.SF3Sprite"; ../../chrtool.exe format "Algernon.SF3Sprite" > tmp; mv tmp "Algernon.SF3Sprite"
echo "Arch Demon.SF3Sprite"; ../../chrtool.exe format "Arch Demon.SF3Sprite" > tmp; mv tmp "Arch Demon.SF3Sprite"
echo "Arch Dragon.SF3Sprite"; ../../chrtool.exe format "Arch Dragon.SF3Sprite" > tmp; mv tmp "Arch Dragon.SF3Sprite"
echo "Ark Hill Priest.SF3Sprite"; ../../chrtool.exe format "Ark Hill Priest.SF3Sprite" > tmp; mv tmp "Ark Hill Priest.SF3Sprite"
echo "Arrawnt.SF3Sprite"; ../../chrtool.exe format "Arrawnt.SF3Sprite" > tmp; mv tmp "Arrawnt.SF3Sprite"
echo "Arthur (P1).SF3Sprite"; ../../chrtool.exe format "Arthur (P1).SF3Sprite" > tmp; mv tmp "Arthur (P1).SF3Sprite"
echo "Arthur (P2).SF3Sprite"; ../../chrtool.exe format "Arthur (P2).SF3Sprite" > tmp; mv tmp "Arthur (P2).SF3Sprite"
echo "Arthur w_o Armour.SF3Sprite"; ../../chrtool.exe format "Arthur w_o Armour.SF3Sprite" > tmp; mv tmp "Arthur w_o Armour.SF3Sprite"
echo "Aspinia Knight.SF3Sprite"; ../../chrtool.exe format "Aspinia Knight.SF3Sprite" > tmp; mv tmp "Aspinia Knight.SF3Sprite"
echo "Aspinia Mage.SF3Sprite"; ../../chrtool.exe format "Aspinia Mage.SF3Sprite" > tmp; mv tmp "Aspinia Mage.SF3Sprite"
echo "Aspinia Soldier (Axe).SF3Sprite"; ../../chrtool.exe format "Aspinia Soldier (Axe).SF3Sprite" > tmp; mv tmp "Aspinia Soldier (Axe).SF3Sprite"
echo "Aspinia Soldier (Crutches).SF3Sprite"; ../../chrtool.exe format "Aspinia Soldier (Crutches).SF3Sprite" > tmp; mv tmp "Aspinia Soldier (Crutches).SF3Sprite"
echo "Aspinia Soldier (Spear).SF3Sprite"; ../../chrtool.exe format "Aspinia Soldier (Spear).SF3Sprite" > tmp; mv tmp "Aspinia Soldier (Spear).SF3Sprite"
echo "Aspinia Soldier (Sword).SF3Sprite"; ../../chrtool.exe format "Aspinia Soldier (Sword).SF3Sprite" > tmp; mv tmp "Aspinia Soldier (Sword).SF3Sprite"
echo "Aspinia Soldier (Weaponless).SF3Sprite"; ../../chrtool.exe format "Aspinia Soldier (Weaponless).SF3Sprite" > tmp; mv tmp "Aspinia Soldier (Weaponless).SF3Sprite"
echo "Assassin.SF3Sprite"; ../../chrtool.exe format "Assassin.SF3Sprite" > tmp; mv tmp "Assassin.SF3Sprite"
echo "Baby Dragon.SF3Sprite"; ../../chrtool.exe format "Baby Dragon.SF3Sprite" > tmp; mv tmp "Baby Dragon.SF3Sprite"
echo "Baby Penn (Blue Shorts, Yellow Shell up Top).SF3Sprite"; ../../chrtool.exe format "Baby Penn (Blue Shorts, Yellow Shell up Top).SF3Sprite" > tmp; mv tmp "Baby Penn (Blue Shorts, Yellow Shell up Top).SF3Sprite"
echo "Baby Penn (Blue, Green Shell on Top and Bottom).SF3Sprite"; ../../chrtool.exe format "Baby Penn (Blue, Green Shell on Top and Bottom).SF3Sprite" > tmp; mv tmp "Baby Penn (Blue, Green Shell on Top and Bottom).SF3Sprite"
echo "Baby Penn (Cyan, Orange Shell, Glasses).SF3Sprite"; ../../chrtool.exe format "Baby Penn (Cyan, Orange Shell, Glasses).SF3Sprite" > tmp; mv tmp "Baby Penn (Cyan, Orange Shell, Glasses).SF3Sprite"
echo "Baby Penn (Full Pink Shell w_ Purple Braids).SF3Sprite"; ../../chrtool.exe format "Baby Penn (Full Pink Shell w_ Purple Braids).SF3Sprite" > tmp; mv tmp "Baby Penn (Full Pink Shell w_ Purple Braids).SF3Sprite"
echo "Baby Penn (Light Pink w_ Yellow Hair and Light Pink Braids).SF3Sprite"; ../../chrtool.exe format "Baby Penn (Light Pink w_ Yellow Hair and Light Pink Braids).SF3Sprite" > tmp; mv tmp "Baby Penn (Light Pink w_ Yellow Hair and Light Pink Braids).SF3Sprite"
echo "Baby Penn (Purple w_ Green Shell).SF3Sprite"; ../../chrtool.exe format "Baby Penn (Purple w_ Green Shell).SF3Sprite" > tmp; mv tmp "Baby Penn (Purple w_ Green Shell).SF3Sprite"
echo "Baby Penn (Sea Green w_ Blue Suit, Bow Tie, and Hat).SF3Sprite"; ../../chrtool.exe format "Baby Penn (Sea Green w_ Blue Suit, Bow Tie, and Hat).SF3Sprite" > tmp; mv tmp "Baby Penn (Sea Green w_ Blue Suit, Bow Tie, and Hat).SF3Sprite"
echo "Bald, Shirtless Burly Man (Shovel).SF3Sprite"; ../../chrtool.exe format "Bald, Shirtless Burly Man (Shovel).SF3Sprite" > tmp; mv tmp "Bald, Shirtless Burly Man (Shovel).SF3Sprite"
echo "Bald, Shirtless Burly Man.SF3Sprite"; ../../chrtool.exe format "Bald, Shirtless Burly Man.SF3Sprite" > tmp; mv tmp "Bald, Shirtless Burly Man.SF3Sprite"
echo "Balding Old Man w_ Red Cloak and Cane.SF3Sprite"; ../../chrtool.exe format "Balding Old Man w_ Red Cloak and Cane.SF3Sprite" > tmp; mv tmp "Balding Old Man w_ Red Cloak and Cane.SF3Sprite"
echo "Bartender.SF3Sprite"; ../../chrtool.exe format "Bartender.SF3Sprite" > tmp; mv tmp "Bartender.SF3Sprite"
echo "Basanda (Staff).SF3Sprite"; ../../chrtool.exe format "Basanda (Staff).SF3Sprite" > tmp; mv tmp "Basanda (Staff).SF3Sprite"
echo "Basanda.SF3Sprite"; ../../chrtool.exe format "Basanda.SF3Sprite" > tmp; mv tmp "Basanda.SF3Sprite"
echo "Bat.SF3Sprite"; ../../chrtool.exe format "Bat.SF3Sprite" > tmp; mv tmp "Bat.SF3Sprite"
echo "Bear w_ Fish.SF3Sprite"; ../../chrtool.exe format "Bear w_ Fish.SF3Sprite" > tmp; mv tmp "Bear w_ Fish.SF3Sprite"
echo "Benetram (Prototype 2).SF3Sprite"; ../../chrtool.exe format "Benetram (Prototype 2).SF3Sprite" > tmp; mv tmp "Benetram (Prototype 2).SF3Sprite"
echo "Benetram (Prototype).SF3Sprite"; ../../chrtool.exe format "Benetram (Prototype).SF3Sprite" > tmp; mv tmp "Benetram (Prototype).SF3Sprite"
echo "Benetram.SF3Sprite"; ../../chrtool.exe format "Benetram.SF3Sprite" > tmp; mv tmp "Benetram.SF3Sprite"
echo "Bernard (P1).SF3Sprite"; ../../chrtool.exe format "Bernard (P1).SF3Sprite" > tmp; mv tmp "Bernard (P1).SF3Sprite"
echo "Bernard (P2).SF3Sprite"; ../../chrtool.exe format "Bernard (P2).SF3Sprite" > tmp; mv tmp "Bernard (P2).SF3Sprite"
echo "Bernard (U) (Tied_Up).SF3Sprite"; ../../chrtool.exe format "Bernard (U) (Tied_Up).SF3Sprite" > tmp; mv tmp "Bernard (U) (Tied_Up).SF3Sprite"
echo "Bernard (U) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Bernard (U) (Weaponless).SF3Sprite" > tmp; mv tmp "Bernard (U) (Weaponless).SF3Sprite"
echo "Bernard (U).SF3Sprite"; ../../chrtool.exe format "Bernard (U).SF3Sprite" > tmp; mv tmp "Bernard (U).SF3Sprite"
echo "Birdboy.SF3Sprite"; ../../chrtool.exe format "Birdboy.SF3Sprite" > tmp; mv tmp "Birdboy.SF3Sprite"
echo "Birdgirl.SF3Sprite"; ../../chrtool.exe format "Birdgirl.SF3Sprite" > tmp; mv tmp "Birdgirl.SF3Sprite"
echo "Birdman.SF3Sprite"; ../../chrtool.exe format "Birdman.SF3Sprite" > tmp; mv tmp "Birdman.SF3Sprite"
echo "Birdwoman w_ Green Dress (Fynnding's Wife).SF3Sprite"; ../../chrtool.exe format "Birdwoman w_ Green Dress (Fynnding's Wife).SF3Sprite" > tmp; mv tmp "Birdwoman w_ Green Dress (Fynnding's Wife).SF3Sprite"
echo "Black Cat.SF3Sprite"; ../../chrtool.exe format "Black Cat.SF3Sprite" > tmp; mv tmp "Black Cat.SF3Sprite"
echo "Black Dragon.SF3Sprite"; ../../chrtool.exe format "Black Dragon.SF3Sprite" > tmp; mv tmp "Black Dragon.SF3Sprite"
echo "Black Knight.SF3Sprite"; ../../chrtool.exe format "Black Knight.SF3Sprite" > tmp; mv tmp "Black Knight.SF3Sprite"
echo "Blacksmith.SF3Sprite"; ../../chrtool.exe format "Blacksmith.SF3Sprite" > tmp; mv tmp "Blacksmith.SF3Sprite"
echo "Blood Born.SF3Sprite"; ../../chrtool.exe format "Blood Born.SF3Sprite" > tmp; mv tmp "Blood Born.SF3Sprite"
echo "Bloody Knight.SF3Sprite"; ../../chrtool.exe format "Bloody Knight.SF3Sprite" > tmp; mv tmp "Bloody Knight.SF3Sprite"
echo "Blue Dragon (SC3).SF3Sprite"; ../../chrtool.exe format "Blue Dragon (SC3).SF3Sprite" > tmp; mv tmp "Blue Dragon (SC3).SF3Sprite"
echo "Blue Dragon.SF3Sprite"; ../../chrtool.exe format "Blue Dragon.SF3Sprite" > tmp; mv tmp "Blue Dragon.SF3Sprite"
echo "Blue.SF3Sprite"; ../../chrtool.exe format "Blue.SF3Sprite" > tmp; mv tmp "Blue.SF3Sprite"
echo "Bomb.SF3Sprite"; ../../chrtool.exe format "Bomb.SF3Sprite" > tmp; mv tmp "Bomb.SF3Sprite"
echo "Bow Knight (Bow).SF3Sprite"; ../../chrtool.exe format "Bow Knight (Bow).SF3Sprite" > tmp; mv tmp "Bow Knight (Bow).SF3Sprite"
echo "Bow Knight (Crossbow).SF3Sprite"; ../../chrtool.exe format "Bow Knight (Crossbow).SF3Sprite" > tmp; mv tmp "Bow Knight (Crossbow).SF3Sprite"
echo "Bow Knight (Waltz Placeholder).SF3Sprite"; ../../chrtool.exe format "Bow Knight (Waltz Placeholder).SF3Sprite" > tmp; mv tmp "Bow Knight (Waltz Placeholder).SF3Sprite"
echo "Boy Masked Monk w_ Blue Shirt and Yellow+Blue Spotted Hood.SF3Sprite"; ../../chrtool.exe format "Boy Masked Monk w_ Blue Shirt and Yellow+Blue Spotted Hood.SF3Sprite" > tmp; mv tmp "Boy Masked Monk w_ Blue Shirt and Yellow+Blue Spotted Hood.SF3Sprite"
echo "Boy w_ Blue Shirt and Blue Shoes.SF3Sprite"; ../../chrtool.exe format "Boy w_ Blue Shirt and Blue Shoes.SF3Sprite" > tmp; mv tmp "Boy w_ Blue Shirt and Blue Shoes.SF3Sprite"
echo "Boy w_ Blue Shirt and Green Hair.SF3Sprite"; ../../chrtool.exe format "Boy w_ Blue Shirt and Green Hair.SF3Sprite" > tmp; mv tmp "Boy w_ Blue Shirt and Green Hair.SF3Sprite"
echo "Boy w_ Green Shirt.SF3Sprite"; ../../chrtool.exe format "Boy w_ Green Shirt.SF3Sprite" > tmp; mv tmp "Boy w_ Green Shirt.SF3Sprite"
echo "Boy w_ Green+Blue Shirt.SF3Sprite"; ../../chrtool.exe format "Boy w_ Green+Blue Shirt.SF3Sprite" > tmp; mv tmp "Boy w_ Green+Blue Shirt.SF3Sprite"
echo "Boy w_ Grey Shirt _ Toby.SF3Sprite"; ../../chrtool.exe format "Boy w_ Grey Shirt _ Toby.SF3Sprite" > tmp; mv tmp "Boy w_ Grey Shirt _ Toby.SF3Sprite"
echo "Braff (Helmet).SF3Sprite"; ../../chrtool.exe format "Braff (Helmet).SF3Sprite" > tmp; mv tmp "Braff (Helmet).SF3Sprite"
echo "Braff (SC3).SF3Sprite"; ../../chrtool.exe format "Braff (SC3).SF3Sprite" > tmp; mv tmp "Braff (SC3).SF3Sprite"
echo "Braff.SF3Sprite"; ../../chrtool.exe format "Braff.SF3Sprite" > tmp; mv tmp "Braff.SF3Sprite"
echo "Bresby (Big).SF3Sprite"; ../../chrtool.exe format "Bresby (Big).SF3Sprite" > tmp; mv tmp "Bresby (Big).SF3Sprite"
echo "Bresby.SF3Sprite"; ../../chrtool.exe format "Bresby.SF3Sprite" > tmp; mv tmp "Bresby.SF3Sprite"
echo "Brigit (P1).SF3Sprite"; ../../chrtool.exe format "Brigit (P1).SF3Sprite" > tmp; mv tmp "Brigit (P1).SF3Sprite"
echo "Brigit (P2).SF3Sprite"; ../../chrtool.exe format "Brigit (P2).SF3Sprite" > tmp; mv tmp "Brigit (P2).SF3Sprite"
echo "Brown Bird.SF3Sprite"; ../../chrtool.exe format "Brown Bird.SF3Sprite" > tmp; mv tmp "Brown Bird.SF3Sprite"
echo "Brute.SF3Sprite"; ../../chrtool.exe format "Brute.SF3Sprite" > tmp; mv tmp "Brute.SF3Sprite"
echo "Brutus.SF3Sprite"; ../../chrtool.exe format "Brutus.SF3Sprite" > tmp; mv tmp "Brutus.SF3Sprite"
echo "Bugbear.SF3Sprite"; ../../chrtool.exe format "Bugbear.SF3Sprite" > tmp; mv tmp "Bugbear.SF3Sprite"
echo "Bulzome (First Form).SF3Sprite"; ../../chrtool.exe format "Bulzome (First Form).SF3Sprite" > tmp; mv tmp "Bulzome (First Form).SF3Sprite"
echo "Bulzome (Second Form).SF3Sprite"; ../../chrtool.exe format "Bulzome (Second Form).SF3Sprite" > tmp; mv tmp "Bulzome (Second Form).SF3Sprite"
echo "Bulzome Golem.SF3Sprite"; ../../chrtool.exe format "Bulzome Golem.SF3Sprite" > tmp; mv tmp "Bulzome Golem.SF3Sprite"
echo "Bulzome Knight.SF3Sprite"; ../../chrtool.exe format "Bulzome Knight.SF3Sprite" > tmp; mv tmp "Bulzome Knight.SF3Sprite"
echo "Bulzome Lightning Strike.SF3Sprite"; ../../chrtool.exe format "Bulzome Lightning Strike.SF3Sprite" > tmp; mv tmp "Bulzome Lightning Strike.SF3Sprite"
echo "Burly Shirtless Male Masked Monk.SF3Sprite"; ../../chrtool.exe format "Burly Shirtless Male Masked Monk.SF3Sprite" > tmp; mv tmp "Burly Shirtless Male Masked Monk.SF3Sprite"
echo "Burly Worker (Shovel).SF3Sprite"; ../../chrtool.exe format "Burly Worker (Shovel).SF3Sprite" > tmp; mv tmp "Burly Worker (Shovel).SF3Sprite"
echo "Burly Worker.SF3Sprite"; ../../chrtool.exe format "Burly Worker.SF3Sprite" > tmp; mv tmp "Burly Worker.SF3Sprite"
echo "Butler w_ Grey Hair.SF3Sprite"; ../../chrtool.exe format "Butler w_ Grey Hair.SF3Sprite" > tmp; mv tmp "Butler w_ Grey Hair.SF3Sprite"
echo "Butler.SF3Sprite"; ../../chrtool.exe format "Butler.SF3Sprite" > tmp; mv tmp "Butler.SF3Sprite"
echo "Campbell (P1) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Campbell (P1) (Weaponless).SF3Sprite" > tmp; mv tmp "Campbell (P1) (Weaponless).SF3Sprite"
echo "Campbell (P1).SF3Sprite"; ../../chrtool.exe format "Campbell (P1).SF3Sprite" > tmp; mv tmp "Campbell (P1).SF3Sprite"
echo "Campbell (P2) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Campbell (P2) (Weaponless).SF3Sprite" > tmp; mv tmp "Campbell (P2) (Weaponless).SF3Sprite"
echo "Campbell (P2).SF3Sprite"; ../../chrtool.exe format "Campbell (P2).SF3Sprite" > tmp; mv tmp "Campbell (P2).SF3Sprite"
echo "Campbell (U) (Weaponless) (Old).SF3Sprite"; ../../chrtool.exe format "Campbell (U) (Weaponless) (Old).SF3Sprite" > tmp; mv tmp "Campbell (U) (Weaponless) (Old).SF3Sprite"
echo "Campbell (U) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Campbell (U) (Weaponless).SF3Sprite" > tmp; mv tmp "Campbell (U) (Weaponless).SF3Sprite"
echo "Campbell (U).SF3Sprite"; ../../chrtool.exe format "Campbell (U).SF3Sprite" > tmp; mv tmp "Campbell (U).SF3Sprite"
echo "Cannon Ball Splash.SF3Sprite"; ../../chrtool.exe format "Cannon Ball Splash.SF3Sprite" > tmp; mv tmp "Cannon Ball Splash.SF3Sprite"
echo "Cannon Ball.SF3Sprite"; ../../chrtool.exe format "Cannon Ball.SF3Sprite" > tmp; mv tmp "Cannon Ball.SF3Sprite"
echo "Captain Domino.SF3Sprite"; ../../chrtool.exe format "Captain Domino.SF3Sprite" > tmp; mv tmp "Captain Domino.SF3Sprite"
echo "Cat w_ White and Brown Fur.SF3Sprite"; ../../chrtool.exe format "Cat w_ White and Brown Fur.SF3Sprite" > tmp; mv tmp "Cat w_ White and Brown Fur.SF3Sprite"
echo "Cerberus.SF3Sprite"; ../../chrtool.exe format "Cerberus.SF3Sprite" > tmp; mv tmp "Cerberus.SF3Sprite"
echo "Chef.SF3Sprite"; ../../chrtool.exe format "Chef.SF3Sprite" > tmp; mv tmp "Chef.SF3Sprite"
echo "Chicken.SF3Sprite"; ../../chrtool.exe format "Chicken.SF3Sprite" > tmp; mv tmp "Chicken.SF3Sprite"
echo "Chimera.SF3Sprite"; ../../chrtool.exe format "Chimera.SF3Sprite" > tmp; mv tmp "Chimera.SF3Sprite"
echo "Church Priest (Female).SF3Sprite"; ../../chrtool.exe format "Church Priest (Female).SF3Sprite" > tmp; mv tmp "Church Priest (Female).SF3Sprite"
echo "Church Priest (Masked Monk).SF3Sprite"; ../../chrtool.exe format "Church Priest (Masked Monk).SF3Sprite" > tmp; mv tmp "Church Priest (Masked Monk).SF3Sprite"
echo "Church Priest.SF3Sprite"; ../../chrtool.exe format "Church Priest.SF3Sprite" > tmp; mv tmp "Church Priest.SF3Sprite"
echo "Clay Doll.SF3Sprite"; ../../chrtool.exe format "Clay Doll.SF3Sprite" > tmp; mv tmp "Clay Doll.SF3Sprite"
echo "Clay Golem.SF3Sprite"; ../../chrtool.exe format "Clay Golem.SF3Sprite" > tmp; mv tmp "Clay Golem.SF3Sprite"
echo "Colossus.SF3Sprite"; ../../chrtool.exe format "Colossus.SF3Sprite" > tmp; mv tmp "Colossus.SF3Sprite"
echo "Conrad.SF3Sprite"; ../../chrtool.exe format "Conrad.SF3Sprite" > tmp; mv tmp "Conrad.SF3Sprite"
echo "Cow.SF3Sprite"; ../../chrtool.exe format "Cow.SF3Sprite" > tmp; mv tmp "Cow.SF3Sprite"
echo "Crewart.SF3Sprite"; ../../chrtool.exe format "Crewart.SF3Sprite" > tmp; mv tmp "Crewart.SF3Sprite"
echo "Cybel (P1).SF3Sprite"; ../../chrtool.exe format "Cybel (P1).SF3Sprite" > tmp; mv tmp "Cybel (P1).SF3Sprite"
echo "Cybel (P2).SF3Sprite"; ../../chrtool.exe format "Cybel (P2).SF3Sprite" > tmp; mv tmp "Cybel (P2).SF3Sprite"
echo "Cybel (U).SF3Sprite"; ../../chrtool.exe format "Cybel (U).SF3Sprite" > tmp; mv tmp "Cybel (U).SF3Sprite"
echo "Cyclops (P1).SF3Sprite"; ../../chrtool.exe format "Cyclops (P1).SF3Sprite" > tmp; mv tmp "Cyclops (P1).SF3Sprite"
echo "Cyclops (P2).SF3Sprite"; ../../chrtool.exe format "Cyclops (P2).SF3Sprite" > tmp; mv tmp "Cyclops (P2).SF3Sprite"
echo "Cyos.SF3Sprite"; ../../chrtool.exe format "Cyos.SF3Sprite" > tmp; mv tmp "Cyos.SF3Sprite"
echo "Dakka.SF3Sprite"; ../../chrtool.exe format "Dakka.SF3Sprite" > tmp; mv tmp "Dakka.SF3Sprite"
echo "Dantares (P1).SF3Sprite"; ../../chrtool.exe format "Dantares (P1).SF3Sprite" > tmp; mv tmp "Dantares (P1).SF3Sprite"
echo "Dantares (P2).SF3Sprite"; ../../chrtool.exe format "Dantares (P2).SF3Sprite" > tmp; mv tmp "Dantares (P2).SF3Sprite"
echo "Dantares (U).SF3Sprite"; ../../chrtool.exe format "Dantares (U).SF3Sprite" > tmp; mv tmp "Dantares (U).SF3Sprite"
echo "Dark Dragon (Head High).SF3Sprite"; ../../chrtool.exe format "Dark Dragon (Head High).SF3Sprite" > tmp; mv tmp "Dark Dragon (Head High).SF3Sprite"
echo "Dark Dragon (Head Low).SF3Sprite"; ../../chrtool.exe format "Dark Dragon (Head Low).SF3Sprite" > tmp; mv tmp "Dark Dragon (Head Low).SF3Sprite"
echo "Dark Gunner.SF3Sprite"; ../../chrtool.exe format "Dark Gunner.SF3Sprite" > tmp; mv tmp "Dark Gunner.SF3Sprite"
echo "Dark Mage.SF3Sprite"; ../../chrtool.exe format "Dark Mage.SF3Sprite" > tmp; mv tmp "Dark Mage.SF3Sprite"
echo "Dark Priest (Green).SF3Sprite"; ../../chrtool.exe format "Dark Priest (Green).SF3Sprite" > tmp; mv tmp "Dark Priest (Green).SF3Sprite"
echo "Dark Priest (Purple).SF3Sprite"; ../../chrtool.exe format "Dark Priest (Purple).SF3Sprite" > tmp; mv tmp "Dark Priest (Purple).SF3Sprite"
echo "Dark Priest (Red).SF3Sprite"; ../../chrtool.exe format "Dark Priest (Red).SF3Sprite" > tmp; mv tmp "Dark Priest (Red).SF3Sprite"
echo "Dark Staff.SF3Sprite"; ../../chrtool.exe format "Dark Staff.SF3Sprite" > tmp; mv tmp "Dark Staff.SF3Sprite"
echo "Darksol.SF3Sprite"; ../../chrtool.exe format "Darksol.SF3Sprite" > tmp; mv tmp "Darksol.SF3Sprite"
echo "David (P1) (With Weight).SF3Sprite"; ../../chrtool.exe format "David (P1) (With Weight).SF3Sprite" > tmp; mv tmp "David (P1) (With Weight).SF3Sprite"
echo "David (P1).SF3Sprite"; ../../chrtool.exe format "David (P1).SF3Sprite" > tmp; mv tmp "David (P1).SF3Sprite"
echo "David (P2) (Speedo).SF3Sprite"; ../../chrtool.exe format "David (P2) (Speedo).SF3Sprite" > tmp; mv tmp "David (P2) (Speedo).SF3Sprite"
echo "David (P2).SF3Sprite"; ../../chrtool.exe format "David (P2).SF3Sprite" > tmp; mv tmp "David (P2).SF3Sprite"
echo "David (U) (Weaponless).SF3Sprite"; ../../chrtool.exe format "David (U) (Weaponless).SF3Sprite" > tmp; mv tmp "David (U) (Weaponless).SF3Sprite"
echo "David (U).SF3Sprite"; ../../chrtool.exe format "David (U).SF3Sprite" > tmp; mv tmp "David (U).SF3Sprite"
echo "Defenda.SF3Sprite"; ../../chrtool.exe format "Defenda.SF3Sprite" > tmp; mv tmp "Defenda.SF3Sprite"
echo "Demon Knight.SF3Sprite"; ../../chrtool.exe format "Demon Knight.SF3Sprite" > tmp; mv tmp "Demon Knight.SF3Sprite"
echo "Dessheren.SF3Sprite"; ../../chrtool.exe format "Dessheren.SF3Sprite" > tmp; mv tmp "Dessheren.SF3Sprite"
echo "Destonia Soldier (Axe).SF3Sprite"; ../../chrtool.exe format "Destonia Soldier (Axe).SF3Sprite" > tmp; mv tmp "Destonia Soldier (Axe).SF3Sprite"
echo "Destonia Soldier (Crutch).SF3Sprite"; ../../chrtool.exe format "Destonia Soldier (Crutch).SF3Sprite" > tmp; mv tmp "Destonia Soldier (Crutch).SF3Sprite"
echo "Destonia Soldier (Spear).SF3Sprite"; ../../chrtool.exe format "Destonia Soldier (Spear).SF3Sprite" > tmp; mv tmp "Destonia Soldier (Spear).SF3Sprite"
echo "Destonia Soldier (Weaponless).SF3Sprite"; ../../chrtool.exe format "Destonia Soldier (Weaponless).SF3Sprite" > tmp; mv tmp "Destonia Soldier (Weaponless).SF3Sprite"
echo "Dog w_ White Fur and Black Ears.SF3Sprite"; ../../chrtool.exe format "Dog w_ White Fur and Black Ears.SF3Sprite" > tmp; mv tmp "Dog w_ White Fur and Black Ears.SF3Sprite"
echo "Domaric (Cane).SF3Sprite"; ../../chrtool.exe format "Domaric (Cane).SF3Sprite" > tmp; mv tmp "Domaric (Cane).SF3Sprite"
echo "Domaric (Old) (Cane).SF3Sprite"; ../../chrtool.exe format "Domaric (Old) (Cane).SF3Sprite" > tmp; mv tmp "Domaric (Old) (Cane).SF3Sprite"
echo "Domaric (Sword).SF3Sprite"; ../../chrtool.exe format "Domaric (Sword).SF3Sprite" > tmp; mv tmp "Domaric (Sword).SF3Sprite"
echo "Donhort (P1) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Donhort (P1) (Weaponless).SF3Sprite" > tmp; mv tmp "Donhort (P1) (Weaponless).SF3Sprite"
echo "Donhort (P1).SF3Sprite"; ../../chrtool.exe format "Donhort (P1).SF3Sprite" > tmp; mv tmp "Donhort (P1).SF3Sprite"
echo "Donhort (P2).SF3Sprite"; ../../chrtool.exe format "Donhort (P2).SF3Sprite" > tmp; mv tmp "Donhort (P2).SF3Sprite"
echo "Donhort Carrying Isabella.SF3Sprite"; ../../chrtool.exe format "Donhort Carrying Isabella.SF3Sprite" > tmp; mv tmp "Donhort Carrying Isabella.SF3Sprite"
echo "Doom Centaur.SF3Sprite"; ../../chrtool.exe format "Doom Centaur.SF3Sprite" > tmp; mv tmp "Doom Centaur.SF3Sprite"
echo "Dove.SF3Sprite"; ../../chrtool.exe format "Dove.SF3Sprite" > tmp; mv tmp "Dove.SF3Sprite"
echo "Dragonewt.SF3Sprite"; ../../chrtool.exe format "Dragonewt.SF3Sprite" > tmp; mv tmp "Dragonewt.SF3Sprite"
echo "Durahan.SF3Sprite"; ../../chrtool.exe format "Durahan.SF3Sprite" > tmp; mv tmp "Durahan.SF3Sprite"
echo "Dwarf Man w_ White Beard _ Duncan.SF3Sprite"; ../../chrtool.exe format "Dwarf Man w_ White Beard _ Duncan.SF3Sprite" > tmp; mv tmp "Dwarf Man w_ White Beard _ Duncan.SF3Sprite"
echo "Dwarf.SF3Sprite"; ../../chrtool.exe format "Dwarf.SF3Sprite" > tmp; mv tmp "Dwarf.SF3Sprite"
echo "Earth Dragon.SF3Sprite"; ../../chrtool.exe format "Earth Dragon.SF3Sprite" > tmp; mv tmp "Earth Dragon.SF3Sprite"
echo "Edmund (P1) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Edmund (P1) (Weaponless).SF3Sprite" > tmp; mv tmp "Edmund (P1) (Weaponless).SF3Sprite"
echo "Edmund (P1).SF3Sprite"; ../../chrtool.exe format "Edmund (P1).SF3Sprite" > tmp; mv tmp "Edmund (P1).SF3Sprite"
echo "Edmund (P2) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Edmund (P2) (Weaponless).SF3Sprite" > tmp; mv tmp "Edmund (P2) (Weaponless).SF3Sprite"
echo "Edmund (P2).SF3Sprite"; ../../chrtool.exe format "Edmund (P2).SF3Sprite" > tmp; mv tmp "Edmund (P2).SF3Sprite"
echo "Eldar (P1, Pink).SF3Sprite"; ../../chrtool.exe format "Eldar (P1, Pink).SF3Sprite" > tmp; mv tmp "Eldar (P1, Pink).SF3Sprite"
echo "Eldar (P1, Purple_Wrong).SF3Sprite"; ../../chrtool.exe format "Eldar (P1, Purple_Wrong).SF3Sprite" > tmp; mv tmp "Eldar (P1, Purple_Wrong).SF3Sprite"
echo "Eldar (P2).SF3Sprite"; ../../chrtool.exe format "Eldar (P2).SF3Sprite" > tmp; mv tmp "Eldar (P2).SF3Sprite"
echo "Eldar (U).SF3Sprite"; ../../chrtool.exe format "Eldar (U).SF3Sprite" > tmp; mv tmp "Eldar (U).SF3Sprite"
echo "Elf Boy w_ Green Hair.SF3Sprite"; ../../chrtool.exe format "Elf Boy w_ Green Hair.SF3Sprite" > tmp; mv tmp "Elf Boy w_ Green Hair.SF3Sprite"
echo "Elf Girl w_ Green Hood.SF3Sprite"; ../../chrtool.exe format "Elf Girl w_ Green Hood.SF3Sprite" > tmp; mv tmp "Elf Girl w_ Green Hood.SF3Sprite"
echo "Elf Man w_ Balding Turquoise Hair (Helmet).SF3Sprite"; ../../chrtool.exe format "Elf Man w_ Balding Turquoise Hair (Helmet).SF3Sprite" > tmp; mv tmp "Elf Man w_ Balding Turquoise Hair (Helmet).SF3Sprite"
echo "Elf Man w_ Balding Turquoise Hair.SF3Sprite"; ../../chrtool.exe format "Elf Man w_ Balding Turquoise Hair.SF3Sprite" > tmp; mv tmp "Elf Man w_ Balding Turquoise Hair.SF3Sprite"
echo "Elf Man w_ Pink Shirt and Balding Brown Hair.SF3Sprite"; ../../chrtool.exe format "Elf Man w_ Pink Shirt and Balding Brown Hair.SF3Sprite" > tmp; mv tmp "Elf Man w_ Pink Shirt and Balding Brown Hair.SF3Sprite"
echo "Elf Woman in Bikini Who Doesn't Like To Be Pushed.SF3Sprite"; ../../chrtool.exe format "Elf Woman in Bikini Who Doesn't Like To Be Pushed.SF3Sprite" > tmp; mv tmp "Elf Woman in Bikini Who Doesn't Like To Be Pushed.SF3Sprite"
echo "Elf Woman w_ Brown Dress and Hair.SF3Sprite"; ../../chrtool.exe format "Elf Woman w_ Brown Dress and Hair.SF3Sprite" > tmp; mv tmp "Elf Woman w_ Brown Dress and Hair.SF3Sprite"
echo "Elf Woman w_ Brown Hood and Orange Hair.SF3Sprite"; ../../chrtool.exe format "Elf Woman w_ Brown Hood and Orange Hair.SF3Sprite" > tmp; mv tmp "Elf Woman w_ Brown Hood and Orange Hair.SF3Sprite"
echo "Elf Woman w_ White Apron.SF3Sprite"; ../../chrtool.exe format "Elf Woman w_ White Apron.SF3Sprite" > tmp; mv tmp "Elf Woman w_ White Apron.SF3Sprite"
echo "Explosion.SF3Sprite"; ../../chrtool.exe format "Explosion.SF3Sprite" > tmp; mv tmp "Explosion.SF3Sprite"
echo "Explosion2.SF3Sprite"; ../../chrtool.exe format "Explosion2.SF3Sprite" > tmp; mv tmp "Explosion2.SF3Sprite"
echo "Fafhard (Helmet).SF3Sprite"; ../../chrtool.exe format "Fafhard (Helmet).SF3Sprite" > tmp; mv tmp "Fafhard (Helmet).SF3Sprite"
echo "Fafhard.SF3Sprite"; ../../chrtool.exe format "Fafhard.SF3Sprite" > tmp; mv tmp "Fafhard.SF3Sprite"
echo "Female Masked Monk w_ Blue Robe, Apron, and Striped Hood.SF3Sprite"; ../../chrtool.exe format "Female Masked Monk w_ Blue Robe, Apron, and Striped Hood.SF3Sprite" > tmp; mv tmp "Female Masked Monk w_ Blue Robe, Apron, and Striped Hood.SF3Sprite"
echo "Female Masked Monk w_ Grey+Green Dress.SF3Sprite"; ../../chrtool.exe format "Female Masked Monk w_ Grey+Green Dress.SF3Sprite" > tmp; mv tmp "Female Masked Monk w_ Grey+Green Dress.SF3Sprite"
echo "Female Masked Monk w_ Purple Dress and Checkered Hood.SF3Sprite"; ../../chrtool.exe format "Female Masked Monk w_ Purple Dress and Checkered Hood.SF3Sprite" > tmp; mv tmp "Female Masked Monk w_ Purple Dress and Checkered Hood.SF3Sprite"
echo "Fey (Big).SF3Sprite"; ../../chrtool.exe format "Fey (Big).SF3Sprite" > tmp; mv tmp "Fey (Big).SF3Sprite"
echo "Fey (Quonus Priest).SF3Sprite"; ../../chrtool.exe format "Fey (Quonus Priest).SF3Sprite" > tmp; mv tmp "Fey (Quonus Priest).SF3Sprite"
echo "Fey (Small).SF3Sprite"; ../../chrtool.exe format "Fey (Small).SF3Sprite" > tmp; mv tmp "Fey (Small).SF3Sprite"
echo "Fey Wings (Big).SF3Sprite"; ../../chrtool.exe format "Fey Wings (Big).SF3Sprite" > tmp; mv tmp "Fey Wings (Big).SF3Sprite"
echo "Fey Wings (Small).SF3Sprite"; ../../chrtool.exe format "Fey Wings (Small).SF3Sprite" > tmp; mv tmp "Fey Wings (Small).SF3Sprite"
echo "Fiale.SF3Sprite"; ../../chrtool.exe format "Fiale.SF3Sprite" > tmp; mv tmp "Fiale.SF3Sprite"
echo "Fiderit (Lance).SF3Sprite"; ../../chrtool.exe format "Fiderit (Lance).SF3Sprite" > tmp; mv tmp "Fiderit (Lance).SF3Sprite"
echo "Fiderit.SF3Sprite"; ../../chrtool.exe format "Fiderit.SF3Sprite" > tmp; mv tmp "Fiderit.SF3Sprite"
echo "Firey Poof.SF3Sprite"; ../../chrtool.exe format "Firey Poof.SF3Sprite" > tmp; mv tmp "Firey Poof.SF3Sprite"
echo "Flashing Yellow_Red Light.SF3Sprite"; ../../chrtool.exe format "Flashing Yellow_Red Light.SF3Sprite" > tmp; mv tmp "Flashing Yellow_Red Light.SF3Sprite"
echo "Flower Bouquet.SF3Sprite"; ../../chrtool.exe format "Flower Bouquet.SF3Sprite" > tmp; mv tmp "Flower Bouquet.SF3Sprite"
echo "Flower Girl (With Flowers).SF3Sprite"; ../../chrtool.exe format "Flower Girl (With Flowers).SF3Sprite" > tmp; mv tmp "Flower Girl (With Flowers).SF3Sprite"
echo "Flower Girl.SF3Sprite"; ../../chrtool.exe format "Flower Girl.SF3Sprite" > tmp; mv tmp "Flower Girl.SF3Sprite"
echo "Foothill Village Chief_Sage.SF3Sprite"; ../../chrtool.exe format "Foothill Village Chief_Sage.SF3Sprite" > tmp; mv tmp "Foothill Village Chief_Sage.SF3Sprite"
echo "Frank (P1).SF3Sprite"; ../../chrtool.exe format "Frank (P1).SF3Sprite" > tmp; mv tmp "Frank (P1).SF3Sprite"
echo "Frank (P2).SF3Sprite"; ../../chrtool.exe format "Frank (P2).SF3Sprite" > tmp; mv tmp "Frank (P2).SF3Sprite"
echo "Frank (U).SF3Sprite"; ../../chrtool.exe format "Frank (U).SF3Sprite" > tmp; mv tmp "Frank (U).SF3Sprite"
echo "Franz (Helmet).SF3Sprite"; ../../chrtool.exe format "Franz (Helmet).SF3Sprite" > tmp; mv tmp "Franz (Helmet).SF3Sprite"
echo "Franz.SF3Sprite"; ../../chrtool.exe format "Franz.SF3Sprite" > tmp; mv tmp "Franz.SF3Sprite"
echo "Freeze Ball Pedestal.SF3Sprite"; ../../chrtool.exe format "Freeze Ball Pedestal.SF3Sprite" > tmp; mv tmp "Freeze Ball Pedestal.SF3Sprite"
echo "Fynnding (P1 Alt).SF3Sprite"; ../../chrtool.exe format "Fynnding (P1 Alt).SF3Sprite" > tmp; mv tmp "Fynnding (P1 Alt).SF3Sprite"
echo "Fynnding (P1).SF3Sprite"; ../../chrtool.exe format "Fynnding (P1).SF3Sprite" > tmp; mv tmp "Fynnding (P1).SF3Sprite"
echo "Fynnding (P2).SF3Sprite"; ../../chrtool.exe format "Fynnding (P2).SF3Sprite" > tmp; mv tmp "Fynnding (P2).SF3Sprite"
echo "Galm (Frozen).SF3Sprite"; ../../chrtool.exe format "Galm (Frozen).SF3Sprite" > tmp; mv tmp "Galm (Frozen).SF3Sprite"
echo "Galm.SF3Sprite"; ../../chrtool.exe format "Galm.SF3Sprite" > tmp; mv tmp "Galm.SF3Sprite"
echo "Gargoyle.SF3Sprite"; ../../chrtool.exe format "Gargoyle.SF3Sprite" > tmp; mv tmp "Gargoyle.SF3Sprite"
echo "Garosh (P1) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Garosh (P1) (Weaponless).SF3Sprite" > tmp; mv tmp "Garosh (P1) (Weaponless).SF3Sprite"
echo "Garosh (P1).SF3Sprite"; ../../chrtool.exe format "Garosh (P1).SF3Sprite" > tmp; mv tmp "Garosh (P1).SF3Sprite"
echo "Garosh (P2).SF3Sprite"; ../../chrtool.exe format "Garosh (P2).SF3Sprite" > tmp; mv tmp "Garosh (P2).SF3Sprite"
echo "Garosh (U).SF3Sprite"; ../../chrtool.exe format "Garosh (U).SF3Sprite" > tmp; mv tmp "Garosh (U).SF3Sprite"
echo "Garvin.SF3Sprite"; ../../chrtool.exe format "Garvin.SF3Sprite" > tmp; mv tmp "Garvin.SF3Sprite"
echo "Garzel (Helmet).SF3Sprite"; ../../chrtool.exe format "Garzel (Helmet).SF3Sprite" > tmp; mv tmp "Garzel (Helmet).SF3Sprite"
echo "Garzel.SF3Sprite"; ../../chrtool.exe format "Garzel.SF3Sprite" > tmp; mv tmp "Garzel.SF3Sprite"
echo "Ghoul.SF3Sprite"; ../../chrtool.exe format "Ghoul.SF3Sprite" > tmp; mv tmp "Ghoul.SF3Sprite"
echo "Giant Ant.SF3Sprite"; ../../chrtool.exe format "Giant Ant.SF3Sprite" > tmp; mv tmp "Giant Ant.SF3Sprite"
echo "Giant Armour.SF3Sprite"; ../../chrtool.exe format "Giant Armour.SF3Sprite" > tmp; mv tmp "Giant Armour.SF3Sprite"
echo "Giga Breaker.SF3Sprite"; ../../chrtool.exe format "Giga Breaker.SF3Sprite" > tmp; mv tmp "Giga Breaker.SF3Sprite"
echo "Girl Masked Monk w_ Red Dress and Red+Pink Spotted Hood.SF3Sprite"; ../../chrtool.exe format "Girl Masked Monk w_ Red Dress and Red+Pink Spotted Hood.SF3Sprite" > tmp; mv tmp "Girl Masked Monk w_ Red Dress and Red+Pink Spotted Hood.SF3Sprite"
echo "Girl w_ Blue+Pink Dress and Short Hair.SF3Sprite"; ../../chrtool.exe format "Girl w_ Blue+Pink Dress and Short Hair.SF3Sprite" > tmp; mv tmp "Girl w_ Blue+Pink Dress and Short Hair.SF3Sprite"
echo "Girl w_ Green+Yellow Dress.SF3Sprite"; ../../chrtool.exe format "Girl w_ Green+Yellow Dress.SF3Sprite" > tmp; mv tmp "Girl w_ Green+Yellow Dress.SF3Sprite"
echo "Girl w_ Pink Dress.SF3Sprite"; ../../chrtool.exe format "Girl w_ Pink Dress.SF3Sprite" > tmp; mv tmp "Girl w_ Pink Dress.SF3Sprite"
echo "Girl w_ Red Dress.SF3Sprite"; ../../chrtool.exe format "Girl w_ Red Dress.SF3Sprite" > tmp; mv tmp "Girl w_ Red Dress.SF3Sprite"
echo "Goblin.SF3Sprite"; ../../chrtool.exe format "Goblin.SF3Sprite" > tmp; mv tmp "Goblin.SF3Sprite"
echo "Golem (Big).SF3Sprite"; ../../chrtool.exe format "Golem (Big).SF3Sprite" > tmp; mv tmp "Golem (Big).SF3Sprite"
echo "Golem (Small).SF3Sprite"; ../../chrtool.exe format "Golem (Small).SF3Sprite" > tmp; mv tmp "Golem (Small).SF3Sprite"
echo "Goriate.SF3Sprite"; ../../chrtool.exe format "Goriate.SF3Sprite" > tmp; mv tmp "Goriate.SF3Sprite"
echo "Grace (P1).SF3Sprite"; ../../chrtool.exe format "Grace (P1).SF3Sprite" > tmp; mv tmp "Grace (P1).SF3Sprite"
echo "Grace (P2).SF3Sprite"; ../../chrtool.exe format "Grace (P2).SF3Sprite" > tmp; mv tmp "Grace (P2).SF3Sprite"
echo "Grace (U).SF3Sprite"; ../../chrtool.exe format "Grace (U).SF3Sprite" > tmp; mv tmp "Grace (U).SF3Sprite"
echo "Gracia (Big).SF3Sprite"; ../../chrtool.exe format "Gracia (Big).SF3Sprite" > tmp; mv tmp "Gracia (Big).SF3Sprite"
echo "Gracia (P1) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Gracia (P1) (Weaponless).SF3Sprite" > tmp; mv tmp "Gracia (P1) (Weaponless).SF3Sprite"
echo "Gracia (P1).SF3Sprite"; ../../chrtool.exe format "Gracia (P1).SF3Sprite" > tmp; mv tmp "Gracia (P1).SF3Sprite"
echo "Gracia (P2) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Gracia (P2) (Weaponless).SF3Sprite" > tmp; mv tmp "Gracia (P2) (Weaponless).SF3Sprite"
echo "Gracia (P2).SF3Sprite"; ../../chrtool.exe format "Gracia (P2).SF3Sprite" > tmp; mv tmp "Gracia (P2).SF3Sprite"
echo "Grantack (Old).SF3Sprite"; ../../chrtool.exe format "Grantack (Old).SF3Sprite" > tmp; mv tmp "Grantack (Old).SF3Sprite"
echo "Grantack.SF3Sprite"; ../../chrtool.exe format "Grantack.SF3Sprite" > tmp; mv tmp "Grantack.SF3Sprite"
echo "Green Dragon.SF3Sprite"; ../../chrtool.exe format "Green Dragon.SF3Sprite" > tmp; mv tmp "Green Dragon.SF3Sprite"
echo "Grey Birdman.SF3Sprite"; ../../chrtool.exe format "Grey Birdman.SF3Sprite" > tmp; mv tmp "Grey Birdman.SF3Sprite"
echo "Griffon.SF3Sprite"; ../../chrtool.exe format "Griffon.SF3Sprite" > tmp; mv tmp "Griffon.SF3Sprite"
echo "Guide Statue Beyond The Wall.SF3Sprite"; ../../chrtool.exe format "Guide Statue Beyond The Wall.SF3Sprite" > tmp; mv tmp "Guide Statue Beyond The Wall.SF3Sprite"
echo "Hagane (Black).SF3Sprite"; ../../chrtool.exe format "Hagane (Black).SF3Sprite" > tmp; mv tmp "Hagane (Black).SF3Sprite"
echo "Hagane (Dark Cyan).SF3Sprite"; ../../chrtool.exe format "Hagane (Dark Cyan).SF3Sprite" > tmp; mv tmp "Hagane (Dark Cyan).SF3Sprite"
echo "Hagane (P1).SF3Sprite"; ../../chrtool.exe format "Hagane (P1).SF3Sprite" > tmp; mv tmp "Hagane (P1).SF3Sprite"
echo "Hagane (P2).SF3Sprite"; ../../chrtool.exe format "Hagane (P2).SF3Sprite" > tmp; mv tmp "Hagane (P2).SF3Sprite"
echo "Hagane (Shinobi).SF3Sprite"; ../../chrtool.exe format "Hagane (Shinobi).SF3Sprite" > tmp; mv tmp "Hagane (Shinobi).SF3Sprite"
echo "Harold (P1) (No Tank).SF3Sprite"; ../../chrtool.exe format "Harold (P1) (No Tank).SF3Sprite" > tmp; mv tmp "Harold (P1) (No Tank).SF3Sprite"
echo "Harold (P1) (Tank).SF3Sprite"; ../../chrtool.exe format "Harold (P1) (Tank).SF3Sprite" > tmp; mv tmp "Harold (P1) (Tank).SF3Sprite"
echo "Harold (P2) (No Tank).SF3Sprite"; ../../chrtool.exe format "Harold (P2) (No Tank).SF3Sprite" > tmp; mv tmp "Harold (P2) (No Tank).SF3Sprite"
echo "Harold (P2) (Tank).SF3Sprite"; ../../chrtool.exe format "Harold (P2) (Tank).SF3Sprite" > tmp; mv tmp "Harold (P2) (Tank).SF3Sprite"
echo "Harold's Tank (P1).SF3Sprite"; ../../chrtool.exe format "Harold's Tank (P1).SF3Sprite" > tmp; mv tmp "Harold's Tank (P1).SF3Sprite"
echo "Harpy.SF3Sprite"; ../../chrtool.exe format "Harpy.SF3Sprite" > tmp; mv tmp "Harpy.SF3Sprite"
echo "Hayward (P1).SF3Sprite"; ../../chrtool.exe format "Hayward (P1).SF3Sprite" > tmp; mv tmp "Hayward (P1).SF3Sprite"
echo "Hayward (P2).SF3Sprite"; ../../chrtool.exe format "Hayward (P2).SF3Sprite" > tmp; mv tmp "Hayward (P2).SF3Sprite"
echo "Hayward (Prototype).SF3Sprite"; ../../chrtool.exe format "Hayward (Prototype).SF3Sprite" > tmp; mv tmp "Hayward (Prototype).SF3Sprite"
echo "Hayward (U).SF3Sprite"; ../../chrtool.exe format "Hayward (U).SF3Sprite" > tmp; mv tmp "Hayward (U).SF3Sprite"
echo "Hazuki (P1).SF3Sprite"; ../../chrtool.exe format "Hazuki (P1).SF3Sprite" > tmp; mv tmp "Hazuki (P1).SF3Sprite"
echo "Hazuki (P2).SF3Sprite"; ../../chrtool.exe format "Hazuki (P2).SF3Sprite" > tmp; mv tmp "Hazuki (P2).SF3Sprite"
echo "Hazuki (U).SF3Sprite"; ../../chrtool.exe format "Hazuki (U).SF3Sprite" > tmp; mv tmp "Hazuki (U).SF3Sprite"
echo "Hazuki's Father.SF3Sprite"; ../../chrtool.exe format "Hazuki's Father.SF3Sprite" > tmp; mv tmp "Hazuki's Father.SF3Sprite"
echo "Hedva (P1).SF3Sprite"; ../../chrtool.exe format "Hedva (P1).SF3Sprite" > tmp; mv tmp "Hedva (P1).SF3Sprite"
echo "Hedva (P2) (Without Weapon).SF3Sprite"; ../../chrtool.exe format "Hedva (P2) (Without Weapon).SF3Sprite" > tmp; mv tmp "Hedva (P2) (Without Weapon).SF3Sprite"
echo "Hedva (P2).SF3Sprite"; ../../chrtool.exe format "Hedva (P2).SF3Sprite" > tmp; mv tmp "Hedva (P2).SF3Sprite"
echo "Hedva (U).SF3Sprite"; ../../chrtool.exe format "Hedva (U).SF3Sprite" > tmp; mv tmp "Hedva (U).SF3Sprite"
echo "Hell Hound.SF3Sprite"; ../../chrtool.exe format "Hell Hound.SF3Sprite" > tmp; mv tmp "Hell Hound.SF3Sprite"
echo "Hell Sniper.SF3Sprite"; ../../chrtool.exe format "Hell Sniper.SF3Sprite" > tmp; mv tmp "Hell Sniper.SF3Sprite"
echo "Hell Succubus.SF3Sprite"; ../../chrtool.exe format "Hell Succubus.SF3Sprite" > tmp; mv tmp "Hell Succubus.SF3Sprite"
echo "Hera (P1).SF3Sprite"; ../../chrtool.exe format "Hera (P1).SF3Sprite" > tmp; mv tmp "Hera (P1).SF3Sprite"
echo "Hera (P2).SF3Sprite"; ../../chrtool.exe format "Hera (P2).SF3Sprite" > tmp; mv tmp "Hera (P2).SF3Sprite"
echo "Hermit Crab.SF3Sprite"; ../../chrtool.exe format "Hermit Crab.SF3Sprite" > tmp; mv tmp "Hermit Crab.SF3Sprite"
echo "High Priest.SF3Sprite"; ../../chrtool.exe format "High Priest.SF3Sprite" > tmp; mv tmp "High Priest.SF3Sprite"
echo "High Shinobi.SF3Sprite"; ../../chrtool.exe format "High Shinobi.SF3Sprite" > tmp; mv tmp "High Shinobi.SF3Sprite"
echo "High Wizard.SF3Sprite"; ../../chrtool.exe format "High Wizard.SF3Sprite" > tmp; mv tmp "High Wizard.SF3Sprite"
echo "Hill Giant.SF3Sprite"; ../../chrtool.exe format "Hill Giant.SF3Sprite" > tmp; mv tmp "Hill Giant.SF3Sprite"
echo "Honesty (P1) Carrying Synbios.SF3Sprite"; ../../chrtool.exe format "Honesty (P1) Carrying Synbios.SF3Sprite" > tmp; mv tmp "Honesty (P1) Carrying Synbios.SF3Sprite"
echo "Honesty (P1).SF3Sprite"; ../../chrtool.exe format "Honesty (P1).SF3Sprite" > tmp; mv tmp "Honesty (P1).SF3Sprite"
echo "Honesty (P2) Carrying Synbios.SF3Sprite"; ../../chrtool.exe format "Honesty (P2) Carrying Synbios.SF3Sprite" > tmp; mv tmp "Honesty (P2) Carrying Synbios.SF3Sprite"
echo "Honesty (P2).SF3Sprite"; ../../chrtool.exe format "Honesty (P2).SF3Sprite" > tmp; mv tmp "Honesty (P2).SF3Sprite"
echo "Horst (P1).SF3Sprite"; ../../chrtool.exe format "Horst (P1).SF3Sprite" > tmp; mv tmp "Horst (P1).SF3Sprite"
echo "Horst (P2).SF3Sprite"; ../../chrtool.exe format "Horst (P2).SF3Sprite" > tmp; mv tmp "Horst (P2).SF3Sprite"
echo "Horst (U).SF3Sprite"; ../../chrtool.exe format "Horst (U).SF3Sprite" > tmp; mv tmp "Horst (U).SF3Sprite"
echo "Hunter Elf.SF3Sprite"; ../../chrtool.exe format "Hunter Elf.SF3Sprite" > tmp; mv tmp "Hunter Elf.SF3Sprite"
echo "Hydra.SF3Sprite"; ../../chrtool.exe format "Hydra.SF3Sprite" > tmp; mv tmp "Hydra.SF3Sprite"
echo "Ice Golem.SF3Sprite"; ../../chrtool.exe format "Ice Golem.SF3Sprite" > tmp; mv tmp "Ice Golem.SF3Sprite"
echo "Ice Pillar.SF3Sprite"; ../../chrtool.exe format "Ice Pillar.SF3Sprite" > tmp; mv tmp "Ice Pillar.SF3Sprite"
echo "Imperial Knight.SF3Sprite"; ../../chrtool.exe format "Imperial Knight.SF3Sprite" > tmp; mv tmp "Imperial Knight.SF3Sprite"
echo "Imperial Mage.SF3Sprite"; ../../chrtool.exe format "Imperial Mage.SF3Sprite" > tmp; mv tmp "Imperial Mage.SF3Sprite"
echo "Iom Body.SF3Sprite"; ../../chrtool.exe format "Iom Body.SF3Sprite" > tmp; mv tmp "Iom Body.SF3Sprite"
echo "Iom Serpent.SF3Sprite"; ../../chrtool.exe format "Iom Serpent.SF3Sprite" > tmp; mv tmp "Iom Serpent.SF3Sprite"
echo "Irene (P1).SF3Sprite"; ../../chrtool.exe format "Irene (P1).SF3Sprite" > tmp; mv tmp "Irene (P1).SF3Sprite"
echo "Irene (P2).SF3Sprite"; ../../chrtool.exe format "Irene (P2).SF3Sprite" > tmp; mv tmp "Irene (P2).SF3Sprite"
echo "Irene (Prototype).SF3Sprite"; ../../chrtool.exe format "Irene (Prototype).SF3Sprite" > tmp; mv tmp "Irene (Prototype).SF3Sprite"
echo "Irene (U).SF3Sprite"; ../../chrtool.exe format "Irene (U).SF3Sprite" > tmp; mv tmp "Irene (U).SF3Sprite"
echo "Iria's Boy.SF3Sprite"; ../../chrtool.exe format "Iria's Boy.SF3Sprite" > tmp; mv tmp "Iria's Boy.SF3Sprite"
echo "Iria's Girl.SF3Sprite"; ../../chrtool.exe format "Iria's Girl.SF3Sprite" > tmp; mv tmp "Iria's Girl.SF3Sprite"
echo "Iria.SF3Sprite"; ../../chrtool.exe format "Iria.SF3Sprite" > tmp; mv tmp "Iria.SF3Sprite"
echo "Isabella (P1).SF3Sprite"; ../../chrtool.exe format "Isabella (P1).SF3Sprite" > tmp; mv tmp "Isabella (P1).SF3Sprite"
echo "Isabella (P2).SF3Sprite"; ../../chrtool.exe format "Isabella (P2).SF3Sprite" > tmp; mv tmp "Isabella (P2).SF3Sprite"
echo "Ishahakat.SF3Sprite"; ../../chrtool.exe format "Ishahakat.SF3Sprite" > tmp; mv tmp "Ishahakat.SF3Sprite"
echo "Item Dealer.SF3Sprite"; ../../chrtool.exe format "Item Dealer.SF3Sprite" > tmp; mv tmp "Item Dealer.SF3Sprite"
echo "Jade (P1) (No Tank).SF3Sprite"; ../../chrtool.exe format "Jade (P1) (No Tank).SF3Sprite" > tmp; mv tmp "Jade (P1) (No Tank).SF3Sprite"
echo "Jade (P1) (Tank).SF3Sprite"; ../../chrtool.exe format "Jade (P1) (Tank).SF3Sprite" > tmp; mv tmp "Jade (P1) (Tank).SF3Sprite"
echo "Jade (P2) (No Tank).SF3Sprite"; ../../chrtool.exe format "Jade (P2) (No Tank).SF3Sprite" > tmp; mv tmp "Jade (P2) (No Tank).SF3Sprite"
echo "Jade (P2) (Tank).SF3Sprite"; ../../chrtool.exe format "Jade (P2) (Tank).SF3Sprite" > tmp; mv tmp "Jade (P2) (Tank).SF3Sprite"
echo "Jade's Tank (P1).SF3Sprite"; ../../chrtool.exe format "Jade's Tank (P1).SF3Sprite" > tmp; mv tmp "Jade's Tank (P1).SF3Sprite"
echo "Jane (Weaponless).SF3Sprite"; ../../chrtool.exe format "Jane (Weaponless).SF3Sprite" > tmp; mv tmp "Jane (Weaponless).SF3Sprite"
echo "Jane.SF3Sprite"; ../../chrtool.exe format "Jane.SF3Sprite" > tmp; mv tmp "Jane.SF3Sprite"
echo "Jin Ninja (Green).SF3Sprite"; ../../chrtool.exe format "Jin Ninja (Green).SF3Sprite" > tmp; mv tmp "Jin Ninja (Green).SF3Sprite"
echo "Jubei (P1).SF3Sprite"; ../../chrtool.exe format "Jubei (P1).SF3Sprite" > tmp; mv tmp "Jubei (P1).SF3Sprite"
echo "Jubei (P2).SF3Sprite"; ../../chrtool.exe format "Jubei (P2).SF3Sprite" > tmp; mv tmp "Jubei (P2).SF3Sprite"
echo "Julian (P1) (Big).SF3Sprite"; ../../chrtool.exe format "Julian (P1) (Big).SF3Sprite" > tmp; mv tmp "Julian (P1) (Big).SF3Sprite"
echo "Julian (P1) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Julian (P1) (Weaponless).SF3Sprite" > tmp; mv tmp "Julian (P1) (Weaponless).SF3Sprite"
echo "Julian (P1).SF3Sprite"; ../../chrtool.exe format "Julian (P1).SF3Sprite" > tmp; mv tmp "Julian (P1).SF3Sprite"
echo "Julian (P2) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Julian (P2) (Weaponless).SF3Sprite" > tmp; mv tmp "Julian (P2) (Weaponless).SF3Sprite"
echo "Julian (P2).SF3Sprite"; ../../chrtool.exe format "Julian (P2).SF3Sprite" > tmp; mv tmp "Julian (P2).SF3Sprite"
echo "Julian (U) (Beer).SF3Sprite"; ../../chrtool.exe format "Julian (U) (Beer).SF3Sprite" > tmp; mv tmp "Julian (U) (Beer).SF3Sprite"
echo "Julian (U) (Big).SF3Sprite"; ../../chrtool.exe format "Julian (U) (Big).SF3Sprite" > tmp; mv tmp "Julian (U) (Big).SF3Sprite"
echo "Julian (U) (Shield) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Julian (U) (Shield) (Weaponless).SF3Sprite" > tmp; mv tmp "Julian (U) (Shield) (Weaponless).SF3Sprite"
echo "Julian (U) (Shield).SF3Sprite"; ../../chrtool.exe format "Julian (U) (Shield).SF3Sprite" > tmp; mv tmp "Julian (U) (Shield).SF3Sprite"
echo "Julian (U) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Julian (U) (Weaponless).SF3Sprite" > tmp; mv tmp "Julian (U) (Weaponless).SF3Sprite"
echo "Julian (U).SF3Sprite"; ../../chrtool.exe format "Julian (U).SF3Sprite" > tmp; mv tmp "Julian (U).SF3Sprite"
echo "Justin (P1).SF3Sprite"; ../../chrtool.exe format "Justin (P1).SF3Sprite" > tmp; mv tmp "Justin (P1).SF3Sprite"
echo "Justin (P2).SF3Sprite"; ../../chrtool.exe format "Justin (P2).SF3Sprite" > tmp; mv tmp "Justin (P2).SF3Sprite"
echo "Justin (Unused P1 Alt).SF3Sprite"; ../../chrtool.exe format "Justin (Unused P1 Alt).SF3Sprite" > tmp; mv tmp "Justin (Unused P1 Alt).SF3Sprite"
echo "Justin (Unused P1).SF3Sprite"; ../../chrtool.exe format "Justin (Unused P1).SF3Sprite" > tmp; mv tmp "Justin (Unused P1).SF3Sprite"
echo "Kahn (P1).SF3Sprite"; ../../chrtool.exe format "Kahn (P1).SF3Sprite" > tmp; mv tmp "Kahn (P1).SF3Sprite"
echo "Kahn (P2).SF3Sprite"; ../../chrtool.exe format "Kahn (P2).SF3Sprite" > tmp; mv tmp "Kahn (P2).SF3Sprite"
echo "Kahn (U).SF3Sprite"; ../../chrtool.exe format "Kahn (U).SF3Sprite" > tmp; mv tmp "Kahn (U).SF3Sprite"
echo "Kaiser Guard (Cape).SF3Sprite"; ../../chrtool.exe format "Kaiser Guard (Cape).SF3Sprite" > tmp; mv tmp "Kaiser Guard (Cape).SF3Sprite"
echo "Kaiser Guard.SF3Sprite"; ../../chrtool.exe format "Kaiser Guard.SF3Sprite" > tmp; mv tmp "Kaiser Guard.SF3Sprite"
echo "Kate (P1).SF3Sprite"; ../../chrtool.exe format "Kate (P1).SF3Sprite" > tmp; mv tmp "Kate (P1).SF3Sprite"
echo "Kate (P2).SF3Sprite"; ../../chrtool.exe format "Kate (P2).SF3Sprite" > tmp; mv tmp "Kate (P2).SF3Sprite"
echo "Keeper.SF3Sprite"; ../../chrtool.exe format "Keeper.SF3Sprite" > tmp; mv tmp "Keeper.SF3Sprite"
echo "Key.SF3Sprite"; ../../chrtool.exe format "Key.SF3Sprite" > tmp; mv tmp "Key.SF3Sprite"
echo "Killer Fish.SF3Sprite"; ../../chrtool.exe format "Killer Fish.SF3Sprite" > tmp; mv tmp "Killer Fish.SF3Sprite"
echo "Kraken Arm.SF3Sprite"; ../../chrtool.exe format "Kraken Arm.SF3Sprite" > tmp; mv tmp "Kraken Arm.SF3Sprite"
echo "Kraken Leg.SF3Sprite"; ../../chrtool.exe format "Kraken Leg.SF3Sprite" > tmp; mv tmp "Kraken Leg.SF3Sprite"
echo "Kudan.SF3Sprite"; ../../chrtool.exe format "Kudan.SF3Sprite" > tmp; mv tmp "Kudan.SF3Sprite"
echo "Kyon_Shi.SF3Sprite"; ../../chrtool.exe format "Kyon_Shi.SF3Sprite" > tmp; mv tmp "Kyon_Shi.SF3Sprite"
echo "Large Male Masked Monk w_ Brown Shirt and Blue Hood.SF3Sprite"; ../../chrtool.exe format "Large Male Masked Monk w_ Brown Shirt and Blue Hood.SF3Sprite" > tmp; mv tmp "Large Male Masked Monk w_ Brown Shirt and Blue Hood.SF3Sprite"
echo "Large Man w_ Turquoise Shirt.SF3Sprite"; ../../chrtool.exe format "Large Man w_ Turquoise Shirt.SF3Sprite" > tmp; mv tmp "Large Man w_ Turquoise Shirt.SF3Sprite"
echo "Large Orange Explosion.SF3Sprite"; ../../chrtool.exe format "Large Orange Explosion.SF3Sprite" > tmp; mv tmp "Large Orange Explosion.SF3Sprite"
echo "Large Poof of Black Smoke.SF3Sprite"; ../../chrtool.exe format "Large Poof of Black Smoke.SF3Sprite" > tmp; mv tmp "Large Poof of Black Smoke.SF3Sprite"
echo "Leon (P1).SF3Sprite"; ../../chrtool.exe format "Leon (P1).SF3Sprite" > tmp; mv tmp "Leon (P1).SF3Sprite"
echo "Leon (P2).SF3Sprite"; ../../chrtool.exe format "Leon (P2).SF3Sprite" > tmp; mv tmp "Leon (P2).SF3Sprite"
echo "Lesser Demon.SF3Sprite"; ../../chrtool.exe format "Lesser Demon.SF3Sprite" > tmp; mv tmp "Lesser Demon.SF3Sprite"
echo "Lich.SF3Sprite"; ../../chrtool.exe format "Lich.SF3Sprite" > tmp; mv tmp "Lich.SF3Sprite"
echo "Light Blue Torch Flame.SF3Sprite"; ../../chrtool.exe format "Light Blue Torch Flame.SF3Sprite" > tmp; mv tmp "Light Blue Torch Flame.SF3Sprite"
echo "Light From Staff of Besem.SF3Sprite"; ../../chrtool.exe format "Light From Staff of Besem.SF3Sprite" > tmp; mv tmp "Light From Staff of Besem.SF3Sprite"
echo "Lightning Bolt.SF3Sprite"; ../../chrtool.exe format "Lightning Bolt.SF3Sprite" > tmp; mv tmp "Lightning Bolt.SF3Sprite"
echo "Lizardman.SF3Sprite"; ../../chrtool.exe format "Lizardman.SF3Sprite" > tmp; mv tmp "Lizardman.SF3Sprite"
echo "Mad Garvin.SF3Sprite"; ../../chrtool.exe format "Mad Garvin.SF3Sprite" > tmp; mv tmp "Mad Garvin.SF3Sprite"
echo "Mageron.SF3Sprite"; ../../chrtool.exe format "Mageron.SF3Sprite" > tmp; mv tmp "Mageron.SF3Sprite"
echo "Maid.SF3Sprite"; ../../chrtool.exe format "Maid.SF3Sprite" > tmp; mv tmp "Maid.SF3Sprite"
echo "Male Masked Monk w_ Pink+Green Shirt and Light Blue Hood.SF3Sprite"; ../../chrtool.exe format "Male Masked Monk w_ Pink+Green Shirt and Light Blue Hood.SF3Sprite" > tmp; mv tmp "Male Masked Monk w_ Pink+Green Shirt and Light Blue Hood.SF3Sprite"
echo "Man Bathing in Hot Springs.SF3Sprite"; ../../chrtool.exe format "Man Bathing in Hot Springs.SF3Sprite" > tmp; mv tmp "Man Bathing in Hot Springs.SF3Sprite"
echo "Man in Fancy Blue Uniform.SF3Sprite"; ../../chrtool.exe format "Man in Fancy Blue Uniform.SF3Sprite" > tmp; mv tmp "Man in Fancy Blue Uniform.SF3Sprite"
echo "Man w_ Blue Robes, Orange Cape, and Black+Grey Hair.SF3Sprite"; ../../chrtool.exe format "Man w_ Blue Robes, Orange Cape, and Black+Grey Hair.SF3Sprite" > tmp; mv tmp "Man w_ Blue Robes, Orange Cape, and Black+Grey Hair.SF3Sprite"
echo "Man w_ Blue+Yellow Shirt and Black+Grey Hair.SF3Sprite"; ../../chrtool.exe format "Man w_ Blue+Yellow Shirt and Black+Grey Hair.SF3Sprite" > tmp; mv tmp "Man w_ Blue+Yellow Shirt and Black+Grey Hair.SF3Sprite"
echo "Man w_ Cyan Shirt and Brown Ponytail.SF3Sprite"; ../../chrtool.exe format "Man w_ Cyan Shirt and Brown Ponytail.SF3Sprite" > tmp; mv tmp "Man w_ Cyan Shirt and Brown Ponytail.SF3Sprite"
echo "Man w_ Grey Shirt, Brown Pants, and Blonde Hair.SF3Sprite"; ../../chrtool.exe format "Man w_ Grey Shirt, Brown Pants, and Blonde Hair.SF3Sprite" > tmp; mv tmp "Man w_ Grey Shirt, Brown Pants, and Blonde Hair.SF3Sprite"
echo "Man w_ Orange+Green Shirt.SF3Sprite"; ../../chrtool.exe format "Man w_ Orange+Green Shirt.SF3Sprite" > tmp; mv tmp "Man w_ Orange+Green Shirt.SF3Sprite"
echo "Man w_ Purple Shirt and Short Black Curly Hair.SF3Sprite"; ../../chrtool.exe format "Man w_ Purple Shirt and Short Black Curly Hair.SF3Sprite" > tmp; mv tmp "Man w_ Purple Shirt and Short Black Curly Hair.SF3Sprite"
echo "Man w_ Red Bandana and No Shirt Hammering Wall.SF3Sprite"; ../../chrtool.exe format "Man w_ Red Bandana and No Shirt Hammering Wall.SF3Sprite" > tmp; mv tmp "Man w_ Red Bandana and No Shirt Hammering Wall.SF3Sprite"
echo "Man w_ Red Shirt.SF3Sprite"; ../../chrtool.exe format "Man w_ Red Shirt.SF3Sprite" > tmp; mv tmp "Man w_ Red Shirt.SF3Sprite"
echo "Man w_ White Pants and Spoon.SF3Sprite"; ../../chrtool.exe format "Man w_ White Pants and Spoon.SF3Sprite" > tmp; mv tmp "Man w_ White Pants and Spoon.SF3Sprite"
echo "Man w_ White Shirt and Dark Skin.SF3Sprite"; ../../chrtool.exe format "Man w_ White Shirt and Dark Skin.SF3Sprite" > tmp; mv tmp "Man w_ White Shirt and Dark Skin.SF3Sprite"
echo "Margaret.SF3Sprite"; ../../chrtool.exe format "Margaret.SF3Sprite" > tmp; mv tmp "Margaret.SF3Sprite"
echo "Marky (P1).SF3Sprite"; ../../chrtool.exe format "Marky (P1).SF3Sprite" > tmp; mv tmp "Marky (P1).SF3Sprite"
echo "Marky (P2).SF3Sprite"; ../../chrtool.exe format "Marky (P2).SF3Sprite" > tmp; mv tmp "Marky (P2).SF3Sprite"
echo "Masked Mage (Black).SF3Sprite"; ../../chrtool.exe format "Masked Mage (Black).SF3Sprite" > tmp; mv tmp "Masked Mage (Black).SF3Sprite"
echo "Masked Mage (Green).SF3Sprite"; ../../chrtool.exe format "Masked Mage (Green).SF3Sprite" > tmp; mv tmp "Masked Mage (Green).SF3Sprite"
echo "Masked Mage (Grey).SF3Sprite"; ../../chrtool.exe format "Masked Mage (Grey).SF3Sprite" > tmp; mv tmp "Masked Mage (Grey).SF3Sprite"
echo "Masked Mage (Purple) (Maskless) (With Flowers).SF3Sprite"; ../../chrtool.exe format "Masked Mage (Purple) (Maskless) (With Flowers).SF3Sprite" > tmp; mv tmp "Masked Mage (Purple) (Maskless) (With Flowers).SF3Sprite"
echo "Masked Mage (Purple) (Maskless).SF3Sprite"; ../../chrtool.exe format "Masked Mage (Purple) (Maskless).SF3Sprite" > tmp; mv tmp "Masked Mage (Purple) (Maskless).SF3Sprite"
echo "Masked Mage (Purple).SF3Sprite"; ../../chrtool.exe format "Masked Mage (Purple).SF3Sprite" > tmp; mv tmp "Masked Mage (Purple).SF3Sprite"
echo "Masked Mage (Yellow).SF3Sprite"; ../../chrtool.exe format "Masked Mage (Yellow).SF3Sprite" > tmp; mv tmp "Masked Mage (Yellow).SF3Sprite"
echo "Masked Monk (Blue) (Sceptre).SF3Sprite"; ../../chrtool.exe format "Masked Monk (Blue) (Sceptre).SF3Sprite" > tmp; mv tmp "Masked Monk (Blue) (Sceptre).SF3Sprite"
echo "Masked Monk (Blue) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Masked Monk (Blue) (Weaponless).SF3Sprite" > tmp; mv tmp "Masked Monk (Blue) (Weaponless).SF3Sprite"
echo "Masked Monk (Blue).SF3Sprite"; ../../chrtool.exe format "Masked Monk (Blue).SF3Sprite" > tmp; mv tmp "Masked Monk (Blue).SF3Sprite"
echo "Masked Monk (Brown).SF3Sprite"; ../../chrtool.exe format "Masked Monk (Brown).SF3Sprite" > tmp; mv tmp "Masked Monk (Brown).SF3Sprite"
echo "Masked Monk Blacksmith.SF3Sprite"; ../../chrtool.exe format "Masked Monk Blacksmith.SF3Sprite" > tmp; mv tmp "Masked Monk Blacksmith.SF3Sprite"
echo "Masked Monk Item Dealer.SF3Sprite"; ../../chrtool.exe format "Masked Monk Item Dealer.SF3Sprite" > tmp; mv tmp "Masked Monk Item Dealer.SF3Sprite"
echo "Masked Monk Riding Pegasus.SF3Sprite"; ../../chrtool.exe format "Masked Monk Riding Pegasus.SF3Sprite" > tmp; mv tmp "Masked Monk Riding Pegasus.SF3Sprite"
echo "Masked Monk Weapon Dealer.SF3Sprite"; ../../chrtool.exe format "Masked Monk Weapon Dealer.SF3Sprite" > tmp; mv tmp "Masked Monk Weapon Dealer.SF3Sprite"
echo "Masked Pegasus Carrying Fiale.SF3Sprite"; ../../chrtool.exe format "Masked Pegasus Carrying Fiale.SF3Sprite" > tmp; mv tmp "Masked Pegasus Carrying Fiale.SF3Sprite"
echo "Masked Pegasus Carrying Gracia.SF3Sprite"; ../../chrtool.exe format "Masked Pegasus Carrying Gracia.SF3Sprite" > tmp; mv tmp "Masked Pegasus Carrying Gracia.SF3Sprite"
echo "Masked Pegasus.SF3Sprite"; ../../chrtool.exe format "Masked Pegasus.SF3Sprite" > tmp; mv tmp "Masked Pegasus.SF3Sprite"
echo "Masked Priest (Aquamarine).SF3Sprite"; ../../chrtool.exe format "Masked Priest (Aquamarine).SF3Sprite" > tmp; mv tmp "Masked Priest (Aquamarine).SF3Sprite"
echo "Masked Priest (Red).SF3Sprite"; ../../chrtool.exe format "Masked Priest (Red).SF3Sprite" > tmp; mv tmp "Masked Priest (Red).SF3Sprite"
echo "Masked Priest (White).SF3Sprite"; ../../chrtool.exe format "Masked Priest (White).SF3Sprite" > tmp; mv tmp "Masked Priest (White).SF3Sprite"
echo "Masked Priest Carrying Domaric.SF3Sprite"; ../../chrtool.exe format "Masked Priest Carrying Domaric.SF3Sprite" > tmp; mv tmp "Masked Priest Carrying Domaric.SF3Sprite"
echo "Masqurin (P1).SF3Sprite"; ../../chrtool.exe format "Masqurin (P1).SF3Sprite" > tmp; mv tmp "Masqurin (P1).SF3Sprite"
echo "Masqurin (P2).SF3Sprite"; ../../chrtool.exe format "Masqurin (P2).SF3Sprite" > tmp; mv tmp "Masqurin (P2).SF3Sprite"
echo "Masqurin (U) (With Flowers).SF3Sprite"; ../../chrtool.exe format "Masqurin (U) (With Flowers).SF3Sprite" > tmp; mv tmp "Masqurin (U) (With Flowers).SF3Sprite"
echo "Masqurin (U).SF3Sprite"; ../../chrtool.exe format "Masqurin (U).SF3Sprite" > tmp; mv tmp "Masqurin (U).SF3Sprite"
echo "Master Mage.SF3Sprite"; ../../chrtool.exe format "Master Mage.SF3Sprite" > tmp; mv tmp "Master Mage.SF3Sprite"
echo "Maya Boy in Blue+Yellow.SF3Sprite"; ../../chrtool.exe format "Maya Boy in Blue+Yellow.SF3Sprite" > tmp; mv tmp "Maya Boy in Blue+Yellow.SF3Sprite"
echo "Maya Girl in Green+Pink w_ Orange Pigtails.SF3Sprite"; ../../chrtool.exe format "Maya Girl in Green+Pink w_ Orange Pigtails.SF3Sprite" > tmp; mv tmp "Maya Girl in Green+Pink w_ Orange Pigtails.SF3Sprite"
echo "Maya Man in Blue+Gold.SF3Sprite"; ../../chrtool.exe format "Maya Man in Blue+Gold.SF3Sprite" > tmp; mv tmp "Maya Man in Blue+Gold.SF3Sprite"
echo "Maya Man in Turquoise+Gold.SF3Sprite"; ../../chrtool.exe format "Maya Man in Turquoise+Gold.SF3Sprite" > tmp; mv tmp "Maya Man in Turquoise+Gold.SF3Sprite"
echo "Maya Man in White+Blue (Beer).SF3Sprite"; ../../chrtool.exe format "Maya Man in White+Blue (Beer).SF3Sprite" > tmp; mv tmp "Maya Man in White+Blue (Beer).SF3Sprite"
echo "Maya Man in White+Blue.SF3Sprite"; ../../chrtool.exe format "Maya Man in White+Blue.SF3Sprite" > tmp; mv tmp "Maya Man in White+Blue.SF3Sprite"
echo "Maya Man in Yellow+Blue.SF3Sprite"; ../../chrtool.exe format "Maya Man in Yellow+Blue.SF3Sprite" > tmp; mv tmp "Maya Man in Yellow+Blue.SF3Sprite"
echo "Maya Old Man in Dark Purple Robe and Red+White Cloak.SF3Sprite"; ../../chrtool.exe format "Maya Old Man in Dark Purple Robe and Red+White Cloak.SF3Sprite" > tmp; mv tmp "Maya Old Man in Dark Purple Robe and Red+White Cloak.SF3Sprite"
echo "Maya Old Woman in Dark Purple Dress and Green+Purple Cloak.SF3Sprite"; ../../chrtool.exe format "Maya Old Woman in Dark Purple Dress and Green+Purple Cloak.SF3Sprite" > tmp; mv tmp "Maya Old Woman in Dark Purple Dress and Green+Purple Cloak.SF3Sprite"
echo "Maya Woman in Dark Blue Dress and Blue+White Cloak.SF3Sprite"; ../../chrtool.exe format "Maya Woman in Dark Blue Dress and Blue+White Cloak.SF3Sprite" > tmp; mv tmp "Maya Woman in Dark Blue Dress and Blue+White Cloak.SF3Sprite"
echo "Maya Woman in Green Dress and Pink+White Cloak.SF3Sprite"; ../../chrtool.exe format "Maya Woman in Green Dress and Pink+White Cloak.SF3Sprite" > tmp; mv tmp "Maya Woman in Green Dress and Pink+White Cloak.SF3Sprite"
echo "Maya Woman in Grey Dress and Green+Gold Cloak.SF3Sprite"; ../../chrtool.exe format "Maya Woman in Grey Dress and Green+Gold Cloak.SF3Sprite" > tmp; mv tmp "Maya Woman in Grey Dress and Green+Gold Cloak.SF3Sprite"
echo "Medion (P1) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Medion (P1) (Weaponless).SF3Sprite" > tmp; mv tmp "Medion (P1) (Weaponless).SF3Sprite"
echo "Medion (P1).SF3Sprite"; ../../chrtool.exe format "Medion (P1).SF3Sprite" > tmp; mv tmp "Medion (P1).SF3Sprite"
echo "Medion (P2) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Medion (P2) (Weaponless).SF3Sprite" > tmp; mv tmp "Medion (P2) (Weaponless).SF3Sprite"
echo "Medion (P2).SF3Sprite"; ../../chrtool.exe format "Medion (P2).SF3Sprite" > tmp; mv tmp "Medion (P2).SF3Sprite"
echo "Medion (U) (Big).SF3Sprite"; ../../chrtool.exe format "Medion (U) (Big).SF3Sprite" > tmp; mv tmp "Medion (U) (Big).SF3Sprite"
echo "Medion (U) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Medion (U) (Weaponless).SF3Sprite" > tmp; mv tmp "Medion (U) (Weaponless).SF3Sprite"
echo "Medion (U).SF3Sprite"; ../../chrtool.exe format "Medion (U).SF3Sprite" > tmp; mv tmp "Medion (U).SF3Sprite"
echo "Medium Poof of Black Smoke.SF3Sprite"; ../../chrtool.exe format "Medium Poof of Black Smoke.SF3Sprite" > tmp; mv tmp "Medium Poof of Black Smoke.SF3Sprite"
echo "Mega Loader.SF3Sprite"; ../../chrtool.exe format "Mega Loader.SF3Sprite" > tmp; mv tmp "Mega Loader.SF3Sprite"
echo "Melinda.SF3Sprite"; ../../chrtool.exe format "Melinda.SF3Sprite" > tmp; mv tmp "Melinda.SF3Sprite"
echo "Mercenary.SF3Sprite"; ../../chrtool.exe format "Mercenary.SF3Sprite" > tmp; mv tmp "Mercenary.SF3Sprite"
echo "Messenger Soldier (With Flowers).SF3Sprite"; ../../chrtool.exe format "Messenger Soldier (With Flowers).SF3Sprite" > tmp; mv tmp "Messenger Soldier (With Flowers).SF3Sprite"
echo "Messenger Soldier.SF3Sprite"; ../../chrtool.exe format "Messenger Soldier.SF3Sprite" > tmp; mv tmp "Messenger Soldier.SF3Sprite"
echo "Metal Gunner.SF3Sprite"; ../../chrtool.exe format "Metal Gunner.SF3Sprite" > tmp; mv tmp "Metal Gunner.SF3Sprite"
echo "Minotaur.SF3Sprite"; ../../chrtool.exe format "Minotaur.SF3Sprite" > tmp; mv tmp "Minotaur.SF3Sprite"
echo "Monk w_ Orange Robe.SF3Sprite"; ../../chrtool.exe format "Monk w_ Orange Robe.SF3Sprite" > tmp; mv tmp "Monk w_ Orange Robe.SF3Sprite"
echo "Murasame (P1) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Murasame (P1) (Weaponless).SF3Sprite" > tmp; mv tmp "Murasame (P1) (Weaponless).SF3Sprite"
echo "Murasame (P1).SF3Sprite"; ../../chrtool.exe format "Murasame (P1).SF3Sprite" > tmp; mv tmp "Murasame (P1).SF3Sprite"
echo "Murasame (P2).SF3Sprite"; ../../chrtool.exe format "Murasame (P2).SF3Sprite" > tmp; mv tmp "Murasame (P2).SF3Sprite"
echo "Murasame (U).SF3Sprite"; ../../chrtool.exe format "Murasame (U).SF3Sprite" > tmp; mv tmp "Murasame (U).SF3Sprite"
echo "Necromancer.SF3Sprite"; ../../chrtool.exe format "Necromancer.SF3Sprite" > tmp; mv tmp "Necromancer.SF3Sprite"
echo "Nobleman w_ Purple Hair.SF3Sprite"; ../../chrtool.exe format "Nobleman w_ Purple Hair.SF3Sprite" > tmp; mv tmp "Nobleman w_ Purple Hair.SF3Sprite"
echo "Nobleman w_ Red Coat and Brown Hair.SF3Sprite"; ../../chrtool.exe format "Nobleman w_ Red Coat and Brown Hair.SF3Sprite" > tmp; mv tmp "Nobleman w_ Red Coat and Brown Hair.SF3Sprite"
echo "Noblewoman w_ Green Dress and Blonde Hair.SF3Sprite"; ../../chrtool.exe format "Noblewoman w_ Green Dress and Blonde Hair.SF3Sprite" > tmp; mv tmp "Noblewoman w_ Green Dress and Blonde Hair.SF3Sprite"
echo "None.SF3Sprite"; ../../chrtool.exe format "None.SF3Sprite" > tmp; mv tmp "None.SF3Sprite"
echo "Noon (P1).SF3Sprite"; ../../chrtool.exe format "Noon (P1).SF3Sprite" > tmp; mv tmp "Noon (P1).SF3Sprite"
echo "Noon (P2).SF3Sprite"; ../../chrtool.exe format "Noon (P2).SF3Sprite" > tmp; mv tmp "Noon (P2).SF3Sprite"
echo "Noon (U).SF3Sprite"; ../../chrtool.exe format "Noon (U).SF3Sprite" > tmp; mv tmp "Noon (U).SF3Sprite"
echo "Obright (P1).SF3Sprite"; ../../chrtool.exe format "Obright (P1).SF3Sprite" > tmp; mv tmp "Obright (P1).SF3Sprite"
echo "Obright (P2).SF3Sprite"; ../../chrtool.exe format "Obright (P2).SF3Sprite" > tmp; mv tmp "Obright (P2).SF3Sprite"
echo "Obright (U).SF3Sprite"; ../../chrtool.exe format "Obright (U).SF3Sprite" > tmp; mv tmp "Obright (U).SF3Sprite"
echo "Ogra (P1).SF3Sprite"; ../../chrtool.exe format "Ogra (P1).SF3Sprite" > tmp; mv tmp "Ogra (P1).SF3Sprite"
echo "Old Man Bathing in Hot Springs.SF3Sprite"; ../../chrtool.exe format "Old Man Bathing in Hot Springs.SF3Sprite" > tmp; mv tmp "Old Man Bathing in Hot Springs.SF3Sprite"
echo "Old Man Masked Monk w_ Green Robe, Cane, and Grey Hood.SF3Sprite"; ../../chrtool.exe format "Old Man Masked Monk w_ Green Robe, Cane, and Grey Hood.SF3Sprite" > tmp; mv tmp "Old Man Masked Monk w_ Green Robe, Cane, and Grey Hood.SF3Sprite"
echo "Old Man w_ Green Robe.SF3Sprite"; ../../chrtool.exe format "Old Man w_ Green Robe.SF3Sprite" > tmp; mv tmp "Old Man w_ Green Robe.SF3Sprite"
echo "Old Man.SF3Sprite"; ../../chrtool.exe format "Old Man.SF3Sprite" > tmp; mv tmp "Old Man.SF3Sprite"
echo "Old Woman Bathing in Hot Springs.SF3Sprite"; ../../chrtool.exe format "Old Woman Bathing in Hot Springs.SF3Sprite" > tmp; mv tmp "Old Woman Bathing in Hot Springs.SF3Sprite"
echo "Old Woman w_ Green+Yellow Dress and Dark Skin.SF3Sprite"; ../../chrtool.exe format "Old Woman w_ Green+Yellow Dress and Dark Skin.SF3Sprite" > tmp; mv tmp "Old Woman w_ Green+Yellow Dress and Dark Skin.SF3Sprite"
echo "Old Woman w_ Grey+Turquoise+Gold Dress and Cane.SF3Sprite"; ../../chrtool.exe format "Old Woman w_ Grey+Turquoise+Gold Dress and Cane.SF3Sprite" > tmp; mv tmp "Old Woman w_ Grey+Turquoise+Gold Dress and Cane.SF3Sprite"
echo "Old Woman w_ Purple Robe.SF3Sprite"; ../../chrtool.exe format "Old Woman w_ Purple Robe.SF3Sprite" > tmp; mv tmp "Old Woman w_ Purple Robe.SF3Sprite"
echo "Old Woman.SF3Sprite"; ../../chrtool.exe format "Old Woman.SF3Sprite" > tmp; mv tmp "Old Woman.SF3Sprite"
echo "Oneanera.SF3Sprite"; ../../chrtool.exe format "Oneanera.SF3Sprite" > tmp; mv tmp "Oneanera.SF3Sprite"
echo "Orange Dragon.SF3Sprite"; ../../chrtool.exe format "Orange Dragon.SF3Sprite" > tmp; mv tmp "Orange Dragon.SF3Sprite"
echo "Palsis.SF3Sprite"; ../../chrtool.exe format "Palsis.SF3Sprite" > tmp; mv tmp "Palsis.SF3Sprite"
echo "Pappets (P1).SF3Sprite"; ../../chrtool.exe format "Pappets (P1).SF3Sprite" > tmp; mv tmp "Pappets (P1).SF3Sprite"
echo "Pappets (P2).SF3Sprite"; ../../chrtool.exe format "Pappets (P2).SF3Sprite" > tmp; mv tmp "Pappets (P2).SF3Sprite"
echo "Pegasus Knight.SF3Sprite"; ../../chrtool.exe format "Pegasus Knight.SF3Sprite" > tmp; mv tmp "Pegasus Knight.SF3Sprite"
echo "Pendolf (P1) (Life Ring).SF3Sprite"; ../../chrtool.exe format "Pendolf (P1) (Life Ring).SF3Sprite" > tmp; mv tmp "Pendolf (P1) (Life Ring).SF3Sprite"
echo "Pendolf (P1).SF3Sprite"; ../../chrtool.exe format "Pendolf (P1).SF3Sprite" > tmp; mv tmp "Pendolf (P1).SF3Sprite"
echo "Pendolf (P2).SF3Sprite"; ../../chrtool.exe format "Pendolf (P2).SF3Sprite" > tmp; mv tmp "Pendolf (P2).SF3Sprite"
echo "Penko (P1) (No Shell).SF3Sprite"; ../../chrtool.exe format "Penko (P1) (No Shell).SF3Sprite" > tmp; mv tmp "Penko (P1) (No Shell).SF3Sprite"
echo "Penko (P1).SF3Sprite"; ../../chrtool.exe format "Penko (P1).SF3Sprite" > tmp; mv tmp "Penko (P1).SF3Sprite"
echo "Penko (P2).SF3Sprite"; ../../chrtool.exe format "Penko (P2).SF3Sprite" > tmp; mv tmp "Penko (P2).SF3Sprite"
echo "Penko (U) (NoShell).SF3Sprite"; ../../chrtool.exe format "Penko (U) (NoShell).SF3Sprite" > tmp; mv tmp "Penko (U) (NoShell).SF3Sprite"
echo "Penko (U).SF3Sprite"; ../../chrtool.exe format "Penko (U).SF3Sprite" > tmp; mv tmp "Penko (U).SF3Sprite"
echo "Penko Egg.SF3Sprite"; ../../chrtool.exe format "Penko Egg.SF3Sprite" > tmp; mv tmp "Penko Egg.SF3Sprite"
echo "Penn (P1) (No Shell).SF3Sprite"; ../../chrtool.exe format "Penn (P1) (No Shell).SF3Sprite" > tmp; mv tmp "Penn (P1) (No Shell).SF3Sprite"
echo "Penn (P1).SF3Sprite"; ../../chrtool.exe format "Penn (P1).SF3Sprite" > tmp; mv tmp "Penn (P1).SF3Sprite"
echo "Penn (P2).SF3Sprite"; ../../chrtool.exe format "Penn (P2).SF3Sprite" > tmp; mv tmp "Penn (P2).SF3Sprite"
echo "Penn (U) (No Shell).SF3Sprite"; ../../chrtool.exe format "Penn (U) (No Shell).SF3Sprite" > tmp; mv tmp "Penn (U) (No Shell).SF3Sprite"
echo "Penn (U).SF3Sprite"; ../../chrtool.exe format "Penn (U).SF3Sprite" > tmp; mv tmp "Penn (U).SF3Sprite"
echo "Penn Egg.SF3Sprite"; ../../chrtool.exe format "Penn Egg.SF3Sprite" > tmp; mv tmp "Penn Egg.SF3Sprite"
echo "Pig.SF3Sprite"; ../../chrtool.exe format "Pig.SF3Sprite" > tmp; mv tmp "Pig.SF3Sprite"
echo "Popping Bubble.SF3Sprite"; ../../chrtool.exe format "Popping Bubble.SF3Sprite" > tmp; mv tmp "Popping Bubble.SF3Sprite"
echo "Priest.SF3Sprite"; ../../chrtool.exe format "Priest.SF3Sprite" > tmp; mv tmp "Priest.SF3Sprite"
echo "Primula (P1).SF3Sprite"; ../../chrtool.exe format "Primula (P1).SF3Sprite" > tmp; mv tmp "Primula (P1).SF3Sprite"
echo "Primula (P2).SF3Sprite"; ../../chrtool.exe format "Primula (P2).SF3Sprite" > tmp; mv tmp "Primula (P2).SF3Sprite"
echo "Produn (P1) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Produn (P1) (Weaponless).SF3Sprite" > tmp; mv tmp "Produn (P1) (Weaponless).SF3Sprite"
echo "Produn (P1).SF3Sprite"; ../../chrtool.exe format "Produn (P1).SF3Sprite" > tmp; mv tmp "Produn (P1).SF3Sprite"
echo "Produn (P2).SF3Sprite"; ../../chrtool.exe format "Produn (P2).SF3Sprite" > tmp; mv tmp "Produn (P2).SF3Sprite"
echo "Queen Worm.SF3Sprite"; ../../chrtool.exe format "Queen Worm.SF3Sprite" > tmp; mv tmp "Queen Worm.SF3Sprite"
echo "Rabbit.SF3Sprite"; ../../chrtool.exe format "Rabbit.SF3Sprite" > tmp; mv tmp "Rabbit.SF3Sprite"
echo "Rainblood Bishop (Cape).SF3Sprite"; ../../chrtool.exe format "Rainblood Bishop (Cape).SF3Sprite" > tmp; mv tmp "Rainblood Bishop (Cape).SF3Sprite"
echo "Rainblood Bishop (Capeless).SF3Sprite"; ../../chrtool.exe format "Rainblood Bishop (Capeless).SF3Sprite" > tmp; mv tmp "Rainblood Bishop (Capeless).SF3Sprite"
echo "Rainblood King (Cape).SF3Sprite"; ../../chrtool.exe format "Rainblood King (Cape).SF3Sprite" > tmp; mv tmp "Rainblood King (Cape).SF3Sprite"
echo "Rainblood King (Capeless).SF3Sprite"; ../../chrtool.exe format "Rainblood King (Capeless).SF3Sprite" > tmp; mv tmp "Rainblood King (Capeless).SF3Sprite"
echo "Rainblood Knight (Cape).SF3Sprite"; ../../chrtool.exe format "Rainblood Knight (Cape).SF3Sprite" > tmp; mv tmp "Rainblood Knight (Cape).SF3Sprite"
echo "Rainblood Knight (Capeless).SF3Sprite"; ../../chrtool.exe format "Rainblood Knight (Capeless).SF3Sprite" > tmp; mv tmp "Rainblood Knight (Capeless).SF3Sprite"
echo "Rainblood Pawn (Cape).SF3Sprite"; ../../chrtool.exe format "Rainblood Pawn (Cape).SF3Sprite" > tmp; mv tmp "Rainblood Pawn (Cape).SF3Sprite"
echo "Rainblood Pawn (Capeless).SF3Sprite"; ../../chrtool.exe format "Rainblood Pawn (Capeless).SF3Sprite" > tmp; mv tmp "Rainblood Pawn (Capeless).SF3Sprite"
echo "Rainblood Queen (Cape).SF3Sprite"; ../../chrtool.exe format "Rainblood Queen (Cape).SF3Sprite" > tmp; mv tmp "Rainblood Queen (Cape).SF3Sprite"
echo "Rainblood Queen (Capeless).SF3Sprite"; ../../chrtool.exe format "Rainblood Queen (Capeless).SF3Sprite" > tmp; mv tmp "Rainblood Queen (Capeless).SF3Sprite"
echo "Rainblood Rook (Cape).SF3Sprite"; ../../chrtool.exe format "Rainblood Rook (Cape).SF3Sprite" > tmp; mv tmp "Rainblood Rook (Cape).SF3Sprite"
echo "Rainblood Rook (Capeless).SF3Sprite"; ../../chrtool.exe format "Rainblood Rook (Capeless).SF3Sprite" > tmp; mv tmp "Rainblood Rook (Capeless).SF3Sprite"
echo "Ratchet in Suit (P1).SF3Sprite"; ../../chrtool.exe format "Ratchet in Suit (P1).SF3Sprite" > tmp; mv tmp "Ratchet in Suit (P1).SF3Sprite"
echo "Ratchet in Suit (P2).SF3Sprite"; ../../chrtool.exe format "Ratchet in Suit (P2).SF3Sprite" > tmp; mv tmp "Ratchet in Suit (P2).SF3Sprite"
echo "Ratchet in Suit (U).SF3Sprite"; ../../chrtool.exe format "Ratchet in Suit (U).SF3Sprite" > tmp; mv tmp "Ratchet in Suit (U).SF3Sprite"
echo "Ratchet w_o Suit.SF3Sprite"; ../../chrtool.exe format "Ratchet w_o Suit.SF3Sprite" > tmp; mv tmp "Ratchet w_o Suit.SF3Sprite"
echo "Ratchet's Suit.SF3Sprite"; ../../chrtool.exe format "Ratchet's Suit.SF3Sprite" > tmp; mv tmp "Ratchet's Suit.SF3Sprite"
echo "Red Dragon.SF3Sprite"; ../../chrtool.exe format "Red Dragon.SF3Sprite" > tmp; mv tmp "Red Dragon.SF3Sprite"
echo "Resting Burly Worker.SF3Sprite"; ../../chrtool.exe format "Resting Burly Worker.SF3Sprite" > tmp; mv tmp "Resting Burly Worker.SF3Sprite"
echo "Resting Old Woman.SF3Sprite"; ../../chrtool.exe format "Resting Old Woman.SF3Sprite" > tmp; mv tmp "Resting Old Woman.SF3Sprite"
echo "Rin Ninja (Blue).SF3Sprite"; ../../chrtool.exe format "Rin Ninja (Blue).SF3Sprite" > tmp; mv tmp "Rin Ninja (Blue).SF3Sprite"
echo "Robby (P1).SF3Sprite"; ../../chrtool.exe format "Robby (P1).SF3Sprite" > tmp; mv tmp "Robby (P1).SF3Sprite"
echo "Robby (P2).SF3Sprite"; ../../chrtool.exe format "Robby (P2).SF3Sprite" > tmp; mv tmp "Robby (P2).SF3Sprite"
echo "Rock (P1).SF3Sprite"; ../../chrtool.exe format "Rock (P1).SF3Sprite" > tmp; mv tmp "Rock (P1).SF3Sprite"
echo "Rock (P2).SF3Sprite"; ../../chrtool.exe format "Rock (P2).SF3Sprite" > tmp; mv tmp "Rock (P2).SF3Sprite"
echo "Rock (U).SF3Sprite"; ../../chrtool.exe format "Rock (U).SF3Sprite" > tmp; mv tmp "Rock (U).SF3Sprite"
echo "Rock Thrown By Kid.SF3Sprite"; ../../chrtool.exe format "Rock Thrown By Kid.SF3Sprite" > tmp; mv tmp "Rock Thrown By Kid.SF3Sprite"
echo "Rogan (Alt).SF3Sprite"; ../../chrtool.exe format "Rogan (Alt).SF3Sprite" > tmp; mv tmp "Rogan (Alt).SF3Sprite"
echo "Rogan (P1).SF3Sprite"; ../../chrtool.exe format "Rogan (P1).SF3Sprite" > tmp; mv tmp "Rogan (P1).SF3Sprite"
echo "Rollie (P1).SF3Sprite"; ../../chrtool.exe format "Rollie (P1).SF3Sprite" > tmp; mv tmp "Rollie (P1).SF3Sprite"
echo "Rollie (P2).SF3Sprite"; ../../chrtool.exe format "Rollie (P2).SF3Sprite" > tmp; mv tmp "Rollie (P2).SF3Sprite"
echo "Royal Guard (Mace).SF3Sprite"; ../../chrtool.exe format "Royal Guard (Mace).SF3Sprite" > tmp; mv tmp "Royal Guard (Mace).SF3Sprite"
echo "Royal Guard (Spear).SF3Sprite"; ../../chrtool.exe format "Royal Guard (Spear).SF3Sprite" > tmp; mv tmp "Royal Guard (Spear).SF3Sprite"
echo "Sailor (Bag).SF3Sprite"; ../../chrtool.exe format "Sailor (Bag).SF3Sprite" > tmp; mv tmp "Sailor (Bag).SF3Sprite"
echo "Sailor.SF3Sprite"; ../../chrtool.exe format "Sailor.SF3Sprite" > tmp; mv tmp "Sailor.SF3Sprite"
echo "Saint.SF3Sprite"; ../../chrtool.exe format "Saint.SF3Sprite" > tmp; mv tmp "Saint.SF3Sprite"
echo "Salamander.SF3Sprite"; ../../chrtool.exe format "Salamander.SF3Sprite" > tmp; mv tmp "Salamander.SF3Sprite"
echo "Sandworm.SF3Sprite"; ../../chrtool.exe format "Sandworm.SF3Sprite" > tmp; mv tmp "Sandworm.SF3Sprite"
echo "Saraband Guard (Arrows in Back).SF3Sprite"; ../../chrtool.exe format "Saraband Guard (Arrows in Back).SF3Sprite" > tmp; mv tmp "Saraband Guard (Arrows in Back).SF3Sprite"
echo "Saraband Guard (In Chair).SF3Sprite"; ../../chrtool.exe format "Saraband Guard (In Chair).SF3Sprite" > tmp; mv tmp "Saraband Guard (In Chair).SF3Sprite"
echo "Saraband Guard.SF3Sprite"; ../../chrtool.exe format "Saraband Guard.SF3Sprite" > tmp; mv tmp "Saraband Guard.SF3Sprite"
echo "Saraband Knight.SF3Sprite"; ../../chrtool.exe format "Saraband Knight.SF3Sprite" > tmp; mv tmp "Saraband Knight.SF3Sprite"
echo "Scaven.SF3Sprite"; ../../chrtool.exe format "Scaven.SF3Sprite" > tmp; mv tmp "Scaven.SF3Sprite"
echo "Scholar w_ White Wig.SF3Sprite"; ../../chrtool.exe format "Scholar w_ White Wig.SF3Sprite" > tmp; mv tmp "Scholar w_ White Wig.SF3Sprite"
echo "Scholar.SF3Sprite"; ../../chrtool.exe format "Scholar.SF3Sprite" > tmp; mv tmp "Scholar.SF3Sprite"
echo "Scissor Crab.SF3Sprite"; ../../chrtool.exe format "Scissor Crab.SF3Sprite" > tmp; mv tmp "Scissor Crab.SF3Sprite"
echo "Scruffy Man w_ Short Black Hair and Beard.SF3Sprite"; ../../chrtool.exe format "Scruffy Man w_ Short Black Hair and Beard.SF3Sprite" > tmp; mv tmp "Scruffy Man w_ Short Black Hair and Beard.SF3Sprite"
echo "Sea Gull.SF3Sprite"; ../../chrtool.exe format "Sea Gull.SF3Sprite" > tmp; mv tmp "Sea Gull.SF3Sprite"
echo "Seven Dwarves (1_7).SF3Sprite"; ../../chrtool.exe format "Seven Dwarves (1_7).SF3Sprite" > tmp; mv tmp "Seven Dwarves (1_7).SF3Sprite"
echo "Seven Dwarves (2_7).SF3Sprite"; ../../chrtool.exe format "Seven Dwarves (2_7).SF3Sprite" > tmp; mv tmp "Seven Dwarves (2_7).SF3Sprite"
echo "Seven Dwarves (3_7).SF3Sprite"; ../../chrtool.exe format "Seven Dwarves (3_7).SF3Sprite" > tmp; mv tmp "Seven Dwarves (3_7).SF3Sprite"
echo "Seven Dwarves (4_7).SF3Sprite"; ../../chrtool.exe format "Seven Dwarves (4_7).SF3Sprite" > tmp; mv tmp "Seven Dwarves (4_7).SF3Sprite"
echo "Seven Dwarves (5_7).SF3Sprite"; ../../chrtool.exe format "Seven Dwarves (5_7).SF3Sprite" > tmp; mv tmp "Seven Dwarves (5_7).SF3Sprite"
echo "Seven Dwarves (6_7).SF3Sprite"; ../../chrtool.exe format "Seven Dwarves (6_7).SF3Sprite" > tmp; mv tmp "Seven Dwarves (6_7).SF3Sprite"
echo "Seven Dwarves (7_7).SF3Sprite"; ../../chrtool.exe format "Seven Dwarves (7_7).SF3Sprite" > tmp; mv tmp "Seven Dwarves (7_7).SF3Sprite"
echo "Sheep.SF3Sprite"; ../../chrtool.exe format "Sheep.SF3Sprite" > tmp; mv tmp "Sheep.SF3Sprite"
echo "Shiraf.SF3Sprite"; ../../chrtool.exe format "Shiraf.SF3Sprite" > tmp; mv tmp "Shiraf.SF3Sprite"
echo "Silver Knight.SF3Sprite"; ../../chrtool.exe format "Silver Knight.SF3Sprite" > tmp; mv tmp "Silver Knight.SF3Sprite"
echo "Skeleton.SF3Sprite"; ../../chrtool.exe format "Skeleton.SF3Sprite" > tmp; mv tmp "Skeleton.SF3Sprite"
echo "Skull Fish.SF3Sprite"; ../../chrtool.exe format "Skull Fish.SF3Sprite" > tmp; mv tmp "Skull Fish.SF3Sprite"
echo "Skull Mage.SF3Sprite"; ../../chrtool.exe format "Skull Mage.SF3Sprite" > tmp; mv tmp "Skull Mage.SF3Sprite"
echo "Skull Warrior.SF3Sprite"; ../../chrtool.exe format "Skull Warrior.SF3Sprite" > tmp; mv tmp "Skull Warrior.SF3Sprite"
echo "Slash Bat.SF3Sprite"; ../../chrtool.exe format "Slash Bat.SF3Sprite" > tmp; mv tmp "Slash Bat.SF3Sprite"
echo "Small Icons.SF3Sprite"; ../../chrtool.exe format "Small Icons.SF3Sprite" > tmp; mv tmp "Small Icons.SF3Sprite"
echo "Small Poof of Brown Smoke.SF3Sprite"; ../../chrtool.exe format "Small Poof of Brown Smoke.SF3Sprite" > tmp; mv tmp "Small Poof of Brown Smoke.SF3Sprite"
echo "Small Poof of Grey Smoke.SF3Sprite"; ../../chrtool.exe format "Small Poof of Grey Smoke.SF3Sprite" > tmp; mv tmp "Small Poof of Grey Smoke.SF3Sprite"
echo "Small Torch Flame.SF3Sprite"; ../../chrtool.exe format "Small Torch Flame.SF3Sprite" > tmp; mv tmp "Small Torch Flame.SF3Sprite"
echo "Sniper Elf.SF3Sprite"; ../../chrtool.exe format "Sniper Elf.SF3Sprite" > tmp; mv tmp "Sniper Elf.SF3Sprite"
echo "Sniper.SF3Sprite"; ../../chrtool.exe format "Sniper.SF3Sprite" > tmp; mv tmp "Sniper.SF3Sprite"
echo "Sorcerer.SF3Sprite"; ../../chrtool.exe format "Sorcerer.SF3Sprite" > tmp; mv tmp "Sorcerer.SF3Sprite"
echo "Sphere of Darkness.SF3Sprite"; ../../chrtool.exe format "Sphere of Darkness.SF3Sprite" > tmp; mv tmp "Sphere of Darkness.SF3Sprite"
echo "Sphere of Light Around Jane.SF3Sprite"; ../../chrtool.exe format "Sphere of Light Around Jane.SF3Sprite" > tmp; mv tmp "Sphere of Light Around Jane.SF3Sprite"
echo "Spiriel (P1).SF3Sprite"; ../../chrtool.exe format "Spiriel (P1).SF3Sprite" > tmp; mv tmp "Spiriel (P1).SF3Sprite"
echo "Spiriel (P2).SF3Sprite"; ../../chrtool.exe format "Spiriel (P2).SF3Sprite" > tmp; mv tmp "Spiriel (P2).SF3Sprite"
echo "Spiriel (Sc1+2).SF3Sprite"; ../../chrtool.exe format "Spiriel (Sc1+2).SF3Sprite" > tmp; mv tmp "Spiriel (Sc1+2).SF3Sprite"
echo "Squirrel.SF3Sprite"; ../../chrtool.exe format "Squirrel.SF3Sprite" > tmp; mv tmp "Squirrel.SF3Sprite"
echo "Staff of Besem (Yellow).SF3Sprite"; ../../chrtool.exe format "Staff of Besem (Yellow).SF3Sprite" > tmp; mv tmp "Staff of Besem (Yellow).SF3Sprite"
echo "Staff of Besem.SF3Sprite"; ../../chrtool.exe format "Staff of Besem.SF3Sprite" > tmp; mv tmp "Staff of Besem.SF3Sprite"
echo "Steel.SF3Sprite"; ../../chrtool.exe format "Steel.SF3Sprite" > tmp; mv tmp "Steel.SF3Sprite"
echo "Stella.SF3Sprite"; ../../chrtool.exe format "Stella.SF3Sprite" > tmp; mv tmp "Stella.SF3Sprite"
echo "Sting Worm.SF3Sprite"; ../../chrtool.exe format "Sting Worm.SF3Sprite" > tmp; mv tmp "Sting Worm.SF3Sprite"
echo "Strange Yellow Light.SF3Sprite"; ../../chrtool.exe format "Strange Yellow Light.SF3Sprite" > tmp; mv tmp "Strange Yellow Light.SF3Sprite"
echo "Succubus.SF3Sprite"; ../../chrtool.exe format "Succubus.SF3Sprite" > tmp; mv tmp "Succubus.SF3Sprite"
echo "Synbios (Frozen).SF3Sprite"; ../../chrtool.exe format "Synbios (Frozen).SF3Sprite" > tmp; mv tmp "Synbios (Frozen).SF3Sprite"
echo "Synbios (In Hot Springs).SF3Sprite"; ../../chrtool.exe format "Synbios (In Hot Springs).SF3Sprite" > tmp; mv tmp "Synbios (In Hot Springs).SF3Sprite"
echo "Synbios (P1) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Synbios (P1) (Weaponless).SF3Sprite" > tmp; mv tmp "Synbios (P1) (Weaponless).SF3Sprite"
echo "Synbios (P1).SF3Sprite"; ../../chrtool.exe format "Synbios (P1).SF3Sprite" > tmp; mv tmp "Synbios (P1).SF3Sprite"
echo "Synbios (P2) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Synbios (P2) (Weaponless).SF3Sprite" > tmp; mv tmp "Synbios (P2) (Weaponless).SF3Sprite"
echo "Synbios (P2).SF3Sprite"; ../../chrtool.exe format "Synbios (P2).SF3Sprite" > tmp; mv tmp "Synbios (P2).SF3Sprite"
echo "Synbios (U) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Synbios (U) (Weaponless).SF3Sprite" > tmp; mv tmp "Synbios (U) (Weaponless).SF3Sprite"
echo "Synbios (U).SF3Sprite"; ../../chrtool.exe format "Synbios (U).SF3Sprite" > tmp; mv tmp "Synbios (U).SF3Sprite"
echo "Syntesis (P1).SF3Sprite"; ../../chrtool.exe format "Syntesis (P1).SF3Sprite" > tmp; mv tmp "Syntesis (P1).SF3Sprite"
echo "Syntesis (P2).SF3Sprite"; ../../chrtool.exe format "Syntesis (P2).SF3Sprite" > tmp; mv tmp "Syntesis (P2).SF3Sprite"
echo "Syntesis (U) (Old).SF3Sprite"; ../../chrtool.exe format "Syntesis (U) (Old).SF3Sprite" > tmp; mv tmp "Syntesis (U) (Old).SF3Sprite"
echo "Syntesis (U).SF3Sprite"; ../../chrtool.exe format "Syntesis (U).SF3Sprite" > tmp; mv tmp "Syntesis (U).SF3Sprite"
echo "Taros.SF3Sprite"; ../../chrtool.exe format "Taros.SF3Sprite" > tmp; mv tmp "Taros.SF3Sprite"
echo "Thief (Weaponless).SF3Sprite"; ../../chrtool.exe format "Thief (Weaponless).SF3Sprite" > tmp; mv tmp "Thief (Weaponless).SF3Sprite"
echo "Thief.SF3Sprite"; ../../chrtool.exe format "Thief.SF3Sprite" > tmp; mv tmp "Thief.SF3Sprite"
echo "Thousand (P1).SF3Sprite"; ../../chrtool.exe format "Thousand (P1).SF3Sprite" > tmp; mv tmp "Thousand (P1).SF3Sprite"
echo "Thousand (P2).SF3Sprite"; ../../chrtool.exe format "Thousand (P2).SF3Sprite" > tmp; mv tmp "Thousand (P2).SF3Sprite"
echo "Thousand Egg.SF3Sprite"; ../../chrtool.exe format "Thousand Egg.SF3Sprite" > tmp; mv tmp "Thousand Egg.SF3Sprite"
echo "Tied Up Domaric Mask.SF3Sprite"; ../../chrtool.exe format "Tied Up Domaric Mask.SF3Sprite" > tmp; mv tmp "Tied Up Domaric Mask.SF3Sprite"
echo "Tied Up Domaric.SF3Sprite"; ../../chrtool.exe format "Tied Up Domaric.SF3Sprite" > tmp; mv tmp "Tied Up Domaric.SF3Sprite"
echo "Train Conductor.SF3Sprite"; ../../chrtool.exe format "Train Conductor.SF3Sprite" > tmp; mv tmp "Train Conductor.SF3Sprite"
echo "Train Official w_ White Uniform.SF3Sprite"; ../../chrtool.exe format "Train Official w_ White Uniform.SF3Sprite" > tmp; mv tmp "Train Official w_ White Uniform.SF3Sprite"
echo "Transparency.SF3Sprite"; ../../chrtool.exe format "Transparency.SF3Sprite" > tmp; mv tmp "Transparency.SF3Sprite"
echo "Treasure Chest (Unused).SF3Sprite"; ../../chrtool.exe format "Treasure Chest (Unused).SF3Sprite" > tmp; mv tmp "Treasure Chest (Unused).SF3Sprite"
echo "Tristus.SF3Sprite"; ../../chrtool.exe format "Tristus.SF3Sprite" > tmp; mv tmp "Tristus.SF3Sprite"
echo "Turk (P1).SF3Sprite"; ../../chrtool.exe format "Turk (P1).SF3Sprite" > tmp; mv tmp "Turk (P1).SF3Sprite"
echo "Turk (P2).SF3Sprite"; ../../chrtool.exe format "Turk (P2).SF3Sprite" > tmp; mv tmp "Turk (P2).SF3Sprite"
echo "Turk on Ogra (P1).SF3Sprite"; ../../chrtool.exe format "Turk on Ogra (P1).SF3Sprite" > tmp; mv tmp "Turk on Ogra (P1).SF3Sprite"
echo "Turk on Ogra (P2).SF3Sprite"; ../../chrtool.exe format "Turk on Ogra (P2).SF3Sprite" > tmp; mv tmp "Turk on Ogra (P2).SF3Sprite"
echo "Two Kids Holding Hands.SF3Sprite"; ../../chrtool.exe format "Two Kids Holding Hands.SF3Sprite" > tmp; mv tmp "Two Kids Holding Hands.SF3Sprite"
echo "Tybalt (Weaponless).SF3Sprite"; ../../chrtool.exe format "Tybalt (Weaponless).SF3Sprite" > tmp; mv tmp "Tybalt (Weaponless).SF3Sprite"
echo "Tybalt.SF3Sprite"; ../../chrtool.exe format "Tybalt.SF3Sprite" > tmp; mv tmp "Tybalt.SF3Sprite"
echo "Unoma (P1) (Ramen).SF3Sprite"; ../../chrtool.exe format "Unoma (P1) (Ramen).SF3Sprite" > tmp; mv tmp "Unoma (P1) (Ramen).SF3Sprite"
echo "Unoma (P1) (Ramen, Cape).SF3Sprite"; ../../chrtool.exe format "Unoma (P1) (Ramen, Cape).SF3Sprite" > tmp; mv tmp "Unoma (P1) (Ramen, Cape).SF3Sprite"
echo "Unoma (P1).SF3Sprite"; ../../chrtool.exe format "Unoma (P1).SF3Sprite" > tmp; mv tmp "Unoma (P1).SF3Sprite"
echo "Unoma (P2) (Ramen).SF3Sprite"; ../../chrtool.exe format "Unoma (P2) (Ramen).SF3Sprite" > tmp; mv tmp "Unoma (P2) (Ramen).SF3Sprite"
echo "Unoma (P2).SF3Sprite"; ../../chrtool.exe format "Unoma (P2).SF3Sprite" > tmp; mv tmp "Unoma (P2).SF3Sprite"
echo "Uryudo (Old).SF3Sprite"; ../../chrtool.exe format "Uryudo (Old).SF3Sprite" > tmp; mv tmp "Uryudo (Old).SF3Sprite"
echo "Uryudo (P1).SF3Sprite"; ../../chrtool.exe format "Uryudo (P1).SF3Sprite" > tmp; mv tmp "Uryudo (P1).SF3Sprite"
echo "Uryudo (P2).SF3Sprite"; ../../chrtool.exe format "Uryudo (P2).SF3Sprite" > tmp; mv tmp "Uryudo (P2).SF3Sprite"
echo "Uryudo (U).SF3Sprite"; ../../chrtool.exe format "Uryudo (U).SF3Sprite" > tmp; mv tmp "Uryudo (U).SF3Sprite"
echo "Vampire Bat.SF3Sprite"; ../../chrtool.exe format "Vampire Bat.SF3Sprite" > tmp; mv tmp "Vampire Bat.SF3Sprite"
echo "Varlant (Weaponless).SF3Sprite"; ../../chrtool.exe format "Varlant (Weaponless).SF3Sprite" > tmp; mv tmp "Varlant (Weaponless).SF3Sprite"
echo "Villager Child.SF3Sprite"; ../../chrtool.exe format "Villager Child.SF3Sprite" > tmp; mv tmp "Villager Child.SF3Sprite"
echo "Villager Man.SF3Sprite"; ../../chrtool.exe format "Villager Man.SF3Sprite" > tmp; mv tmp "Villager Man.SF3Sprite"
echo "Villager Old Man.SF3Sprite"; ../../chrtool.exe format "Villager Old Man.SF3Sprite" > tmp; mv tmp "Villager Old Man.SF3Sprite"
echo "Villager Woman.SF3Sprite"; ../../chrtool.exe format "Villager Woman.SF3Sprite" > tmp; mv tmp "Villager Woman.SF3Sprite"
echo "Waitress w_ Black Hair.SF3Sprite"; ../../chrtool.exe format "Waitress w_ Black Hair.SF3Sprite" > tmp; mv tmp "Waitress w_ Black Hair.SF3Sprite"
echo "Waitress.SF3Sprite"; ../../chrtool.exe format "Waitress.SF3Sprite" > tmp; mv tmp "Waitress.SF3Sprite"
echo "Waltz (P1).SF3Sprite"; ../../chrtool.exe format "Waltz (P1).SF3Sprite" > tmp; mv tmp "Waltz (P1).SF3Sprite"
echo "Waltz (P2).SF3Sprite"; ../../chrtool.exe format "Waltz (P2).SF3Sprite" > tmp; mv tmp "Waltz (P2).SF3Sprite"
echo "Waltz (U) (Weaponless).SF3Sprite"; ../../chrtool.exe format "Waltz (U) (Weaponless).SF3Sprite" > tmp; mv tmp "Waltz (U) (Weaponless).SF3Sprite"
echo "Waltz (U).SF3Sprite"; ../../chrtool.exe format "Waltz (U).SF3Sprite" > tmp; mv tmp "Waltz (U).SF3Sprite"
echo "Warrior (Rock Placeholder).SF3Sprite"; ../../chrtool.exe format "Warrior (Rock Placeholder).SF3Sprite" > tmp; mv tmp "Warrior (Rock Placeholder).SF3Sprite"
echo "Weapon Dealer.SF3Sprite"; ../../chrtool.exe format "Weapon Dealer.SF3Sprite" > tmp; mv tmp "Weapon Dealer.SF3Sprite"
echo "White Lord.SF3Sprite"; ../../chrtool.exe format "White Lord.SF3Sprite" > tmp; mv tmp "White Lord.SF3Sprite"
echo "Wilmer (Helmet).SF3Sprite"; ../../chrtool.exe format "Wilmer (Helmet).SF3Sprite" > tmp; mv tmp "Wilmer (Helmet).SF3Sprite"
echo "Wilmer.SF3Sprite"; ../../chrtool.exe format "Wilmer.SF3Sprite" > tmp; mv tmp "Wilmer.SF3Sprite"
echo "Wing Knight.SF3Sprite"; ../../chrtool.exe format "Wing Knight.SF3Sprite" > tmp; mv tmp "Wing Knight.SF3Sprite"
echo "Wise Man.SF3Sprite"; ../../chrtool.exe format "Wise Man.SF3Sprite" > tmp; mv tmp "Wise Man.SF3Sprite"
echo "Wolf Baron.SF3Sprite"; ../../chrtool.exe format "Wolf Baron.SF3Sprite" > tmp; mv tmp "Wolf Baron.SF3Sprite"
echo "Woman Bathing in Hot Springs.SF3Sprite"; ../../chrtool.exe format "Woman Bathing in Hot Springs.SF3Sprite" > tmp; mv tmp "Woman Bathing in Hot Springs.SF3Sprite"
echo "Woman Carrying Rice.SF3Sprite"; ../../chrtool.exe format "Woman Carrying Rice.SF3Sprite" > tmp; mv tmp "Woman Carrying Rice.SF3Sprite"
echo "Woman in Bikini w_ Red Parted Hair.SF3Sprite"; ../../chrtool.exe format "Woman in Bikini w_ Red Parted Hair.SF3Sprite" > tmp; mv tmp "Woman in Bikini w_ Red Parted Hair.SF3Sprite"
echo "Woman w_ Baby and Red Dress.SF3Sprite"; ../../chrtool.exe format "Woman w_ Baby and Red Dress.SF3Sprite" > tmp; mv tmp "Woman w_ Baby and Red Dress.SF3Sprite"
echo "Woman w_ Blue Dress and Apron.SF3Sprite"; ../../chrtool.exe format "Woman w_ Blue Dress and Apron.SF3Sprite" > tmp; mv tmp "Woman w_ Blue Dress and Apron.SF3Sprite"
echo "Woman w_ Blue+Yellow Dress and Black Hair.SF3Sprite"; ../../chrtool.exe format "Woman w_ Blue+Yellow Dress and Black Hair.SF3Sprite" > tmp; mv tmp "Woman w_ Blue+Yellow Dress and Black Hair.SF3Sprite"
echo "Woman w_ Brown Dress and White Apron Sweeping w_ Broom.SF3Sprite"; ../../chrtool.exe format "Woman w_ Brown Dress and White Apron Sweeping w_ Broom.SF3Sprite" > tmp; mv tmp "Woman w_ Brown Dress and White Apron Sweeping w_ Broom.SF3Sprite"
echo "Woman w_ Brown Ponytail.SF3Sprite"; ../../chrtool.exe format "Woman w_ Brown Ponytail.SF3Sprite" > tmp; mv tmp "Woman w_ Brown Ponytail.SF3Sprite"
echo "Woman w_ Brown Skirt, Blue Dress, and Blonde Ponytail.SF3Sprite"; ../../chrtool.exe format "Woman w_ Brown Skirt, Blue Dress, and Blonde Ponytail.SF3Sprite" > tmp; mv tmp "Woman w_ Brown Skirt, Blue Dress, and Blonde Ponytail.SF3Sprite"
echo "Woman w_ Green+Blue Dress and Blonde Hair.SF3Sprite"; ../../chrtool.exe format "Woman w_ Green+Blue Dress and Blonde Hair.SF3Sprite" > tmp; mv tmp "Woman w_ Green+Blue Dress and Blonde Hair.SF3Sprite"
echo "Woman w_ Green+Brown Dress and White Apron.SF3Sprite"; ../../chrtool.exe format "Woman w_ Green+Brown Dress and White Apron.SF3Sprite" > tmp; mv tmp "Woman w_ Green+Brown Dress and White Apron.SF3Sprite"
echo "Woman w_ Grey+Purple Dress and Bun.SF3Sprite"; ../../chrtool.exe format "Woman w_ Grey+Purple Dress and Bun.SF3Sprite" > tmp; mv tmp "Woman w_ Grey+Purple Dress and Bun.SF3Sprite"
echo "Woman w_ Pink Dress.SF3Sprite"; ../../chrtool.exe format "Woman w_ Pink Dress.SF3Sprite" > tmp; mv tmp "Woman w_ Pink Dress.SF3Sprite"
echo "Woman w_ Turquoise Dress and Hat.SF3Sprite"; ../../chrtool.exe format "Woman w_ Turquoise Dress and Hat.SF3Sprite" > tmp; mv tmp "Woman w_ Turquoise Dress and Hat.SF3Sprite"
echo "Woman w_ Turquoise+Red Dress and Brown Hair.SF3Sprite"; ../../chrtool.exe format "Woman w_ Turquoise+Red Dress and Brown Hair.SF3Sprite" > tmp; mv tmp "Woman w_ Turquoise+Red Dress and Brown Hair.SF3Sprite"
echo "Woman w_ Yellow+Green Dress and Pinkish Ponytail.SF3Sprite"; ../../chrtool.exe format "Woman w_ Yellow+Green Dress and Pinkish Ponytail.SF3Sprite" > tmp; mv tmp "Woman w_ Yellow+Green Dress and Pinkish Ponytail.SF3Sprite"
echo "Worm.SF3Sprite"; ../../chrtool.exe format "Worm.SF3Sprite" > tmp; mv tmp "Worm.SF3Sprite"
echo "Wyvern.SF3Sprite"; ../../chrtool.exe format "Wyvern.SF3Sprite" > tmp; mv tmp "Wyvern.SF3Sprite"
echo "Yasha (Tied_Up).SF3Sprite"; ../../chrtool.exe format "Yasha (Tied_Up).SF3Sprite" > tmp; mv tmp "Yasha (Tied_Up).SF3Sprite"
echo "Yasha (Weaponless).SF3Sprite"; ../../chrtool.exe format "Yasha (Weaponless).SF3Sprite" > tmp; mv tmp "Yasha (Weaponless).SF3Sprite"
echo "Yasha.SF3Sprite"; ../../chrtool.exe format "Yasha.SF3Sprite" > tmp; mv tmp "Yasha.SF3Sprite"
echo "Yeti.SF3Sprite"; ../../chrtool.exe format "Yeti.SF3Sprite" > tmp; mv tmp "Yeti.SF3Sprite"
echo "Zai Ninja (Purple).SF3Sprite"; ../../chrtool.exe format "Zai Ninja (Purple).SF3Sprite" > tmp; mv tmp "Zai Ninja (Purple).SF3Sprite"
echo "Zeon.SF3Sprite"; ../../chrtool.exe format "Zeon.SF3Sprite" > tmp; mv tmp "Zeon.SF3Sprite"
echo "Zero (P1).SF3Sprite"; ../../chrtool.exe format "Zero (P1).SF3Sprite" > tmp; mv tmp "Zero (P1).SF3Sprite"
echo "Zero (P2).SF3Sprite"; ../../chrtool.exe format "Zero (P2).SF3Sprite" > tmp; mv tmp "Zero (P2).SF3Sprite"
echo "Zero (U).SF3Sprite"; ../../chrtool.exe format "Zero (U).SF3Sprite" > tmp; mv tmp "Zero (U).SF3Sprite"
echo "Zombie.SF3Sprite"; ../../chrtool.exe format "Zombie.SF3Sprite" > tmp; mv tmp "Zombie.SF3Sprite"
