using CommonLib.Attributes;

namespace SF3.Types {
    public enum AITargetType {
        [EnumDisplayName("Leader")]
        Leader   = 0x00,

        [EnumDisplayName("Closest Enemy")]
        Closest  = 0x01,

        [EnumDisplayName("Flag Unit")]
        FlagUnit = 0x02,

        [EnumDisplayName("Location 0x00")] Location00 = 0x32,
        [EnumDisplayName("Location 0x01")] Location01 = 0x33,
        [EnumDisplayName("Location 0x02")] Location02 = 0x34,
        [EnumDisplayName("Location 0x03")] Location03 = 0x35,
        [EnumDisplayName("Location 0x04")] Location04 = 0x36,
        [EnumDisplayName("Location 0x05")] Location05 = 0x37,
        [EnumDisplayName("Location 0x06")] Location06 = 0x38,
        [EnumDisplayName("Location 0x07")] Location07 = 0x39,
        [EnumDisplayName("Location 0x08")] Location08 = 0x3A,
        [EnumDisplayName("Location 0x09")] Location09 = 0x3B,
        [EnumDisplayName("Location 0x0A")] Location0A = 0x3C,
        [EnumDisplayName("Location 0x0B")] Location0B = 0x3D,
        [EnumDisplayName("Location 0x0C")] Location0C = 0x3E,
        [EnumDisplayName("Location 0x0D")] Location0D = 0x3F,
        [EnumDisplayName("Location 0x0E")] Location0E = 0x40,
        [EnumDisplayName("Location 0x0F")] Location0F = 0x41,
        [EnumDisplayName("Location 0x10")] Location10 = 0x42,
        [EnumDisplayName("Location 0x11")] Location11 = 0x43,
        [EnumDisplayName("Location 0x12")] Location12 = 0x44,
        [EnumDisplayName("Location 0x13")] Location13 = 0x45,
        [EnumDisplayName("Location 0x14")] Location14 = 0x46,
        [EnumDisplayName("Location 0x15")] Location15 = 0x47,
        [EnumDisplayName("Location 0x16")] Location16 = 0x48,
        [EnumDisplayName("Location 0x17")] Location17 = 0x49,
        [EnumDisplayName("Location 0x18")] Location18 = 0x4A,
        [EnumDisplayName("Location 0x19")] Location19 = 0x4B,
        [EnumDisplayName("Location 0x1A")] Location1A = 0x4C,
        [EnumDisplayName("Location 0x1B")] Location1B = 0x4D,
        [EnumDisplayName("Location 0x1C")] Location1C = 0x4E,
        [EnumDisplayName("Location 0x1D")] Location1D = 0x4F,
        [EnumDisplayName("Location 0x1E")] Location1E = 0x50,
        [EnumDisplayName("Location 0x1F")] Location1F = 0x51,

        [EnumDisplayName("Enemy 0x80")] Enemy80 = 0x80,
        [EnumDisplayName("Enemy 0x81")] Enemy81 = 0x81,
        [EnumDisplayName("Enemy 0x82")] Enemy82 = 0x82,
        [EnumDisplayName("Enemy 0x83")] Enemy83 = 0x83,
        [EnumDisplayName("Enemy 0x84")] Enemy84 = 0x84,
        [EnumDisplayName("Enemy 0x85")] Enemy85 = 0x85,
        [EnumDisplayName("Enemy 0x86")] Enemy86 = 0x86,
        [EnumDisplayName("Enemy 0x87")] Enemy87 = 0x87,
        [EnumDisplayName("Enemy 0x88")] Enemy88 = 0x88,
        [EnumDisplayName("Enemy 0x89")] Enemy89 = 0x89,
        [EnumDisplayName("Enemy 0x8A")] Enemy8A = 0x8A,
        [EnumDisplayName("Enemy 0x8B")] Enemy8B = 0x8B,
        [EnumDisplayName("Enemy 0x8C")] Enemy8C = 0x8C,
        [EnumDisplayName("Enemy 0x8D")] Enemy8D = 0x8D,
        [EnumDisplayName("Enemy 0x8E")] Enemy8E = 0x8E,
        [EnumDisplayName("Enemy 0x8F")] Enemy8F = 0x8F,
        [EnumDisplayName("Enemy 0x90")] Enemy90 = 0x90,
        [EnumDisplayName("Enemy 0x91")] Enemy91 = 0x91,
        [EnumDisplayName("Enemy 0x92")] Enemy92 = 0x92,
        [EnumDisplayName("Enemy 0x93")] Enemy93 = 0x93,
        [EnumDisplayName("Enemy 0x94")] Enemy94 = 0x94,
        [EnumDisplayName("Enemy 0x95")] Enemy95 = 0x95,
        [EnumDisplayName("Enemy 0x96")] Enemy96 = 0x96,
        [EnumDisplayName("Enemy 0x97")] Enemy97 = 0x97,
        [EnumDisplayName("Enemy 0x98")] Enemy98 = 0x98,
        [EnumDisplayName("Enemy 0x99")] Enemy99 = 0x99,
        [EnumDisplayName("Enemy 0x9A")] Enemy9A = 0x9A,
        [EnumDisplayName("Enemy 0x9B")] Enemy9B = 0x9B,
        [EnumDisplayName("Enemy 0x9C")] Enemy9C = 0x9C,
        [EnumDisplayName("Enemy 0x9D")] Enemy9D = 0x9D,
        [EnumDisplayName("Enemy 0x9E")] Enemy9E = 0x9E,
        [EnumDisplayName("Enemy 0x9F")] Enemy9F = 0x9F,
        [EnumDisplayName("Enemy 0xA0")] EnemyA0 = 0xA0,
        [EnumDisplayName("Enemy 0xA1")] EnemyA1 = 0xA1,
        [EnumDisplayName("Enemy 0xA2")] EnemyA2 = 0xA2,
        [EnumDisplayName("Enemy 0xA3")] EnemyA3 = 0xA3,
        [EnumDisplayName("Enemy 0xA4")] EnemyA4 = 0xA4,
        [EnumDisplayName("Enemy 0xA5")] EnemyA5 = 0xA5,
        [EnumDisplayName("Enemy 0xA6")] EnemyA6 = 0xA6,
        [EnumDisplayName("Enemy 0xA7")] EnemyA7 = 0xA7,
        [EnumDisplayName("Enemy 0xA8")] EnemyA8 = 0xA8,
        [EnumDisplayName("Enemy 0xA9")] EnemyA9 = 0xA9,
        [EnumDisplayName("Enemy 0xAA")] EnemyAA = 0xAA,
        [EnumDisplayName("Enemy 0xAB")] EnemyAB = 0xAB,
        [EnumDisplayName("Enemy 0xAC")] EnemyAC = 0xAC,
        [EnumDisplayName("Enemy 0xAD")] EnemyAD = 0xAD,
        [EnumDisplayName("Enemy 0xAE")] EnemyAE = 0xAE,
        [EnumDisplayName("Enemy 0xAF")] EnemyAF = 0xAF,
        [EnumDisplayName("Enemy 0xB0")] EnemyB0 = 0xB0,
        [EnumDisplayName("Enemy 0xB1")] EnemyB1 = 0xB1,
        [EnumDisplayName("Enemy 0xB2")] EnemyB2 = 0xB2,
        [EnumDisplayName("Enemy 0xB3")] EnemyB3 = 0xB3,
        [EnumDisplayName("Enemy 0xB4")] EnemyB4 = 0xB4,
        [EnumDisplayName("Enemy 0xB5")] EnemyB5 = 0xB5,
        [EnumDisplayName("Enemy 0xB6")] EnemyB6 = 0xB6,
        [EnumDisplayName("Enemy 0xB7")] EnemyB7 = 0xB7,
        [EnumDisplayName("Enemy 0xB8")] EnemyB8 = 0xB8,
        [EnumDisplayName("Enemy 0xB9")] EnemyB9 = 0xB9,
        [EnumDisplayName("Enemy 0xBA")] EnemyBA = 0xBA,
        [EnumDisplayName("Enemy 0xBB")] EnemyBB = 0xBB,
        [EnumDisplayName("Enemy 0xBC")] EnemyBC = 0xBC,
        [EnumDisplayName("Enemy 0xBD")] EnemyBD = 0xBD,
        [EnumDisplayName("Enemy 0xBE")] EnemyBE = 0xBE,
        [EnumDisplayName("Enemy 0xBF")] EnemyBF = 0xBF,

        [EnumDisplayName("Path 0x00")] Path00 = 0xC0,
        [EnumDisplayName("Path 0x01")] Path01 = 0xC1,
        [EnumDisplayName("Path 0x02")] Path02 = 0xC2,
        [EnumDisplayName("Path 0x03")] Path03 = 0xC3,
        [EnumDisplayName("Path 0x04")] Path04 = 0xC4,
        [EnumDisplayName("Path 0x05")] Path05 = 0xC5,
        [EnumDisplayName("Path 0x06")] Path06 = 0xC6,
        [EnumDisplayName("Path 0x07")] Path07 = 0xC7,
        [EnumDisplayName("Path 0x08")] Path08 = 0xC8,
        [EnumDisplayName("Path 0x09")] Path09 = 0xC9,
        [EnumDisplayName("Path 0x0A")] Path0A = 0xCA,
        [EnumDisplayName("Path 0x0B")] Path0B = 0xCB,
        [EnumDisplayName("Path 0x0C")] Path0C = 0xCC,
        [EnumDisplayName("Path 0x0D")] Path0D = 0xCD,
        [EnumDisplayName("Path 0x0E")] Path0E = 0xCE,
        [EnumDisplayName("Path 0x0F")] Path0F = 0xCF,
        [EnumDisplayName("Path 0x10")] Path10 = 0xD0,
        [EnumDisplayName("Path 0x11")] Path11 = 0xD1,
        [EnumDisplayName("Path 0x12")] Path12 = 0xD2,
        [EnumDisplayName("Path 0x13")] Path13 = 0xD3,
        [EnumDisplayName("Path 0x14")] Path14 = 0xD4,
        [EnumDisplayName("Path 0x15")] Path15 = 0xD5,
        [EnumDisplayName("Path 0x16")] Path16 = 0xD6,
        [EnumDisplayName("Path 0x17")] Path17 = 0xD7,
        [EnumDisplayName("Path 0x18")] Path18 = 0xD8,
        [EnumDisplayName("Path 0x19")] Path19 = 0xD9,
        [EnumDisplayName("Path 0x1A")] Path1A = 0xDA,
        [EnumDisplayName("Path 0x1B")] Path1B = 0xDB,
        [EnumDisplayName("Path 0x1C")] Path1C = 0xDC,
        [EnumDisplayName("Path 0x1D")] Path1D = 0xDD,
        [EnumDisplayName("Path 0x1E")] Path1E = 0xDE,
        [EnumDisplayName("Path 0x1F")] Path1F = 0xDF,

        [EnumDisplayName("None")]
        None = 0xFF,
    }
}
