namespace SF3.Types {
    /// <summary>
    /// List of named values for SF3.
    /// </summary>
    public enum NamedValueType {
        ActorScript,
        AITargetType,
        BattleSceneById,
        Character,
        CharacterClass,
        Droprate,
        EffectFileIndex,
        EffectiveType,
        Element,
        EventActionNpcTalk,
        EventActionInspect,
        EventActionInspectFlags,
        EventTriggerDirection,
        EventTriggerInspectType,
        EventTriggerType,
        FileIndex,
        FileIndexWithFFFFFFFF,
        FriendshipBonusType,
        GameFlag,
        Item,
        InteractDirectionBehavior,
        Load,
        ModelDirection,
        ModelInstanceType,
        Monster,
        MonsterForUnit,
        EventTriggerMoveOnTileType,
        EventTriggerUseItemType,
        EventTriggerWarpSound,
        MagicBonus,
        MapUpdateFunc,
        MovementType,
        Music,
        Sex,
        SpawnType,
        Special,
        SpecialAnimation,
        SpecialStatusEffect,
        SpecialType,
        Spell,
        SpellTarget,
        SpellType,
        Sprite,
        SpriteDirectionCount,
        StatType,
        TargetScoreFunc,
        WeaponSpell,
        WeaponType,

        // Special Types
        ConditionalType,
    };
}
